import { pbkdf2 } from '@noble/hashes/pbkdf2';
import { sha256, sha512 } from '@noble/hashes/sha2';
import { assert } from '@repo/assert';
import { getRandomBytes } from '@repo/crypto';
import type { Uint8Array_ } from '@repo/types';
import { BIP39_ALLOWED_ENTROPY_BITS, BIP39_ALLOWED_WORD_COUNTS, type Bip39EntropyBits } from './consts.js';
import { normalizeNfkd } from './helpers/normalizeNfkd.js';
import { parseBinary } from './helpers/parseBinary.js';
import { toBitString } from './helpers/toBitString.js';
import { ENGLISH_WORDLIST } from './wordlists/english.js';

const ENGLISH_WORD_INDEX = new Map<string, number>(ENGLISH_WORDLIST.map((word, index) => [word, index]));

export const generateMnemonic = (entropyBits: Bip39EntropyBits = 128): string => {
  assert(
    Number.isInteger(entropyBits) && BIP39_ALLOWED_ENTROPY_BITS.includes(entropyBits),
    `entropyBits must be one of: ${BIP39_ALLOWED_ENTROPY_BITS.join(', ')}`,
  );

  const entropyLength = entropyBits / 8;
  const entropy = getRandomBytes(entropyLength);

  assert(entropy.length === entropyLength, `getRandomBytes must return exactly ${entropyLength} bytes`);

  return entropyToMnemonic(entropy);
};

/**
 * @see https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic
 */
export const entropyToMnemonic = (entropy: Uint8Array_): string => {
  const entropyBitsLength = (entropy.length * 8) as Bip39EntropyBits;
  assert(BIP39_ALLOWED_ENTROPY_BITS.includes(entropyBitsLength), 'entropyBits must be one of: 128, 160, 192, 224, 256');

  // A checksum is generated by taking the first ENT / 32 bits of its SHA256 hash
  const checksumBitsLength = entropyBitsLength / 32;
  const entropyBits = toBitString(entropy);
  const checksumBits = toBitString(sha256(entropy)).slice(0, checksumBitsLength);
  const bits = entropyBits + checksumBits;

  const words: string[] = [];
  for (let i = 0; i < bits.length; i += 11) {
    const wordIndex = parseBinary(bits.slice(i, i + 11));
    words.push(ENGLISH_WORDLIST[wordIndex]!);
  }

  return words.join(' ');
};

export const mnemonicToEntropy = (mnemonic: string): Uint8Array_ => {
  const normalizedMnemonic = normalizeNfkd(mnemonic).trim();
  assert(normalizedMnemonic.length > 0, 'Mnemonic must not be empty');

  const words = normalizedMnemonic.split(/\s+/u);
  assert(
    BIP39_ALLOWED_WORD_COUNTS.includes(words.length as (typeof BIP39_ALLOWED_WORD_COUNTS)[number]),
    'Mnemonic word count must be one of: 12, 15, 18, 21, 24',
  );

  const indices = words.map((word) => {
    const index = ENGLISH_WORD_INDEX.get(word);
    assert(index !== undefined, `Unknown mnemonic word: ${word}`);

    return index;
  });

  const bits = indices.map((index) => index.toString(2).padStart(11, '0')).join('');
  const entropyBitsLength = Math.floor((bits.length * 32) / 33);
  const checksumBitsLength = bits.length - entropyBitsLength;

  const entropyBytes = new Uint8Array(entropyBitsLength / 8);
  for (let i = 0; i < entropyBytes.length; i += 1) {
    entropyBytes[i] = parseBinary(bits.slice(i * 8, (i + 1) * 8));
  }

  const expectedChecksum = toBitString(sha256(entropyBytes)).slice(0, checksumBitsLength);
  const actualChecksum = bits.slice(entropyBitsLength);

  assert(expectedChecksum === actualChecksum, 'Invalid mnemonic checksum');

  return entropyBytes;
};

export const validateMnemonic = (mnemonic: string): boolean => {
  try {
    void mnemonicToEntropy(mnemonic);
    return true;
  } catch {
    return false;
  }
};

/**
 * @see https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#from-mnemonic-to-seed
 *
 * @param passphrase If a passphrase is not present, an empty string "" is used instead.
 */
export const mnemonicToSeed = (mnemonic: string, passphrase = ''): Uint8Array_ => {
  const normalizedMnemonic = normalizeNfkd(mnemonic);
  const normalizedPassphrase = normalizeNfkd(passphrase);
  const password = new TextEncoder().encode(normalizedMnemonic);
  const salt = new TextEncoder().encode(`mnemonic${normalizedPassphrase}`);

  // To create a binary seed from the mnemonic,
  // we use the PBKDF2 function with a mnemonic sentence (in UTF-8 NFKD)
  // used as the password and the string "mnemonic" + passphrase (again in UTF-8 NFKD)
  // used as the salt.

  // The iteration count is set to 2048 and
  // HMAC-SHA512 is used as the pseudo-random function.
  // The length of the derived key is 512 bits (= 64 bytes).
  return pbkdf2(sha512, password, salt, {
    c: 2048,
    dkLen: 64,
  }) as Uint8Array_;
};
