import type { ValueOfEnum } from '@repo/types';

/**
 * Generated by scripts/generate-slip44-enums.ts from SLIP-0044.
 * Do not edit manually.
 * @see https://raw.githubusercontent.com/satoshilabs/slips/master/slip-0044.md
 */
export const Bip44CoinType = {
  /** BTC | Bitcoin | 0x80000000 */
  Bitcoin: 0,
  /** - | Testnet (all coins) | 0x80000001 */
  BitcoinTestnet: 1,
  /** LTC | Litecoin | 0x80000002 */
  Litecoin: 2,
  /** DOGE | Dogecoin | 0x80000003 */
  Dogecoin: 3,
  /** RDD | Reddcoin | 0x80000004 */
  Reddcoin: 4,
  /** DASH | Dash | 0x80000005 */
  Dash: 5,
  /** PPC | Peercoin | 0x80000006 */
  Peercoin: 6,
  /** NMC | Namecoin | 0x80000007 */
  Namecoin: 7,
  /** FTC | Feathercoin | 0x80000008 */
  Feathercoin: 8,
  /** XCP | Counterparty | 0x80000009 */
  Counterparty: 9,
  /** BLK | Blackcoin | 0x8000000a */
  Blackcoin: 10,
  /** NSR | NuShares | 0x8000000b */
  Nushares: 11,
  /** NBT | NuBits | 0x8000000c */
  Nubits: 12,
  /** MZC | Mazacoin | 0x8000000d */
  Mazacoin: 13,
  /** VIA | Viacoin | 0x8000000e */
  Viacoin: 14,
  /** XCH | ClearingHouse | 0x8000000f */
  Clearinghouse: 15,
  /** RBY | Rubycoin | 0x80000010 */
  Rubycoin: 16,
  /** GRS | Groestlcoin | 0x80000011 */
  Groestlcoin: 17,
  /** DGC | Digitalcoin | 0x80000012 */
  Digitalcoin: 18,
  /** CCN | Cannacoin | 0x80000013 */
  Cannacoin: 19,
  /** DGB | DigiByte | 0x80000014 */
  Digibyte: 20,
  /** - | Open Assets | 0x80000015 */
  OpenAssets: 21,
  /** MONA | Monacoin | 0x80000016 */
  Monacoin: 22,
  /** CLAM | Clams | 0x80000017 */
  Clams: 23,
  /** XPM | Primecoin | 0x80000018 */
  Primecoin: 24,
  /** NEOS | Neoscoin | 0x80000019 */
  Neoscoin: 25,
  /** JBS | Jumbucks | 0x8000001a */
  Jumbucks: 26,
  /** ZRC | ziftrCOIN | 0x8000001b */
  Ziftrcoin: 27,
  /** VTC | Vertcoin | 0x8000001c */
  Vertcoin: 28,
  /** NXT | NXT | 0x8000001d */
  Nxt: 29,
  /** BURST | Burst | 0x8000001e */
  Burst: 30,
  /** MUE | MonetaryUnit | 0x8000001f */
  Monetaryunit: 31,
  /** ZOOM | Zoom | 0x80000020 */
  Zoom: 32,
  /** VASH | Virtual Cash | 0x80000021 */
  VirtualCash: 33,
  /** CDN | Canada eCoin | 0x80000022 */
  CanadaEcoin: 34,
  /** SDC | ShadowCash | 0x80000023 */
  Shadowcash: 35,
  /** PKB | ParkByte | 0x80000024 */
  Parkbyte: 36,
  /** PND | Pandacoin | 0x80000025 */
  Pandacoin: 37,
  /** START | StartCOIN | 0x80000026 */
  Startcoin: 38,
  /** MOIN | MOIN | 0x80000027 */
  Moin: 39,
  /** EXP | Expanse | 0x80000028 */
  Expanse: 40,
  /** EMC2 | Einsteinium | 0x80000029 */
  Einsteinium: 41,
  /** DCR | Decred | 0x8000002a */
  Decred: 42,
  /** XEM | NEM | 0x8000002b */
  Nem: 43,
  /** PART | Particl | 0x8000002c */
  Particl: 44,
  /** ARG | Argentum (dead) | 0x8000002d */
  ArgentumDead: 45,
  /** - | Libertas | 0x8000002e */
  Libertas: 46,
  /** - | Posw coin | 0x8000002f */
  PoswCoin: 47,
  /** SHR | Shreeji | 0x80000030 */
  Shreeji: 48,
  /** GCR | Global Currency Reserve (GCRcoin) | 0x80000031 */
  GlobalCurrencyReserveGcrcoin: 49,
  /** NVC | Novacoin | 0x80000032 */
  Novacoin: 50,
  /** AC | Asiacoin | 0x80000033 */
  Asiacoin: 51,
  /** BTCD | BitcoinDark | 0x80000034 */
  Bitcoindark: 52,
  /** DOPE | Dopecoin | 0x80000035 */
  Dopecoin: 53,
  /** TPC | Templecoin | 0x80000036 */
  Templecoin: 54,
  /** AIB | AIB | 0x80000037 */
  Aib: 55,
  /** EDRC | EDRCoin | 0x80000038 */
  Edrcoin: 56,
  /** SYS | Syscoin | 0x80000039 */
  Syscoin: 57,
  /** SLR | Solarcoin | 0x8000003a */
  Solarcoin: 58,
  /** SMLY | Smileycoin | 0x8000003b */
  Smileycoin: 59,
  /** ETH | Ether | 0x8000003c */
  Ether: 60,
  /** ETC | Ether Classic | 0x8000003d */
  EtherClassic: 61,
  /** PSB | Pesobit | 0x8000003e */
  Pesobit: 62,
  /** LDCN | Landcoin (dead) | 0x8000003f */
  LandcoinDead: 63,
  /** - | Open Chain | 0x80000040 */
  OpenChain: 64,
  /** XBC | Bitcoinplus | 0x80000041 */
  Bitcoinplus: 65,
  /** IOP | Internet of People | 0x80000042 */
  InternetOfPeople: 66,
  /** NXS | Nexus | 0x80000043 */
  Nexus: 67,
  /** INSN | InsaneCoin | 0x80000044 */
  Insanecoin: 68,
  /** OK | OKCash | 0x80000045 */
  Okcash: 69,
  /** BRIT | BritCoin | 0x80000046 */
  Britcoin: 70,
  /** CMP | Compcoin | 0x80000047 */
  Compcoin: 71,
  /** CRW | Crown | 0x80000048 */
  Crown: 72,
  /** BELA | BelaCoin | 0x80000049 */
  Belacoin: 73,
  /** ICX | ICON | 0x8000004a */
  Icon: 74,
  /** FJC | FujiCoin | 0x8000004b */
  Fujicoin: 75,
  /** MIX | MIX | 0x8000004c */
  Mix: 76,
  /** XVG | Verge Currency | 0x8000004d */
  VergeCurrency: 77,
  /** EFL | Electronic Gulden | 0x8000004e */
  ElectronicGulden: 78,
  /** CLUB | ClubCoin | 0x8000004f */
  Clubcoin: 79,
  /** RICHX | RichCoin | 0x80000050 */
  Richcoin: 80,
  /** POT | Potcoin | 0x80000051 */
  Potcoin: 81,
  /** QRK | Quarkcoin | 0x80000052 */
  Quarkcoin: 82,
  /** TRC | Terracoin | 0x80000053 */
  Terracoin: 83,
  /** GRC | Gridcoin | 0x80000054 */
  Gridcoin: 84,
  /** AUR | Auroracoin | 0x80000055 */
  Auroracoin: 85,
  /** IXC | IXCoin | 0x80000056 */
  Ixcoin: 86,
  /** NLG | Gulden | 0x80000057 */
  Gulden: 87,
  /** BITB | BitBean | 0x80000058 */
  Bitbean: 88,
  /** BTA | Bata | 0x80000059 */
  Bata: 89,
  /** XMY | Myriadcoin | 0x8000005a */
  Myriadcoin: 90,
  /** BSD | BitSend | 0x8000005b */
  Bitsend: 91,
  /** UNO | Unobtanium | 0x8000005c */
  Unobtanium: 92,
  /** MTR | MasterTrader | 0x8000005d */
  Mastertrader: 93,
  /** GB | GoldBlocks | 0x8000005e */
  Goldblocks: 94,
  /** SHM | Saham | 0x8000005f */
  Saham: 95,
  /** CRX | Chronos | 0x80000060 */
  Chronos: 96,
  /** BIQ | Ubiquoin | 0x80000061 */
  Ubiquoin: 97,
  /** EVO | Evotion | 0x80000062 */
  Evotion: 98,
  /** STO | SaveTheOcean | 0x80000063 */
  Savetheocean: 99,
  /** BIGUP | BigUp | 0x80000064 */
  Bigup: 100,
  /** GAME | GameCredits | 0x80000065 */
  Gamecredits: 101,
  /** DLC | Dollarcoins | 0x80000066 */
  Dollarcoins: 102,
  /** ZYD | Zayedcoin | 0x80000067 */
  Zayedcoin: 103,
  /** DBIC | Dubaicoin | 0x80000068 */
  Dubaicoin: 104,
  /** STRAT | Stratis | 0x80000069 */
  Stratis: 105,
  /** SH | Shilling | 0x8000006a */
  Shilling: 106,
  /** MARS | MarsCoin | 0x8000006b */
  Marscoin: 107,
  /** UBQ | Ubiq | 0x8000006c */
  Ubiq: 108,
  /** PTC | Pesetacoin | 0x8000006d */
  Pesetacoin: 109,
  /** NRO | Neurocoin | 0x8000006e */
  Neurocoin: 110,
  /** ARK | ARK | 0x8000006f */
  Ark: 111,
  /** USC | UltimateSecureCashMain | 0x80000070 */
  Ultimatesecurecashmain: 112,
  /** THC | Hempcoin | 0x80000071 */
  Hempcoin: 113,
  /** LINX | Linx | 0x80000072 */
  Linx: 114,
  /** ECN | Ecoin | 0x80000073 */
  Ecoin: 115,
  /** DNR | Denarius | 0x80000074 */
  Denarius: 116,
  /** PINK | Pinkcoin | 0x80000075 */
  Pinkcoin: 117,
  /** ATOM | Atom | 0x80000076 */
  Atom: 118,
  /** PIVX | Pivx | 0x80000077 */
  Pivx: 119,
  /** FLASH | Flashcoin | 0x80000078 */
  Flashcoin: 120,
  /** ZEN | Zencash | 0x80000079 */
  Zencash: 121,
  /** PUT | Putincoin | 0x8000007a */
  Putincoin: 122,
  /** ZNY | BitZeny | 0x8000007b */
  Bitzeny: 123,
  /** UNIFY | Unify | 0x8000007c */
  Unify: 124,
  /** XST | StealthCoin | 0x8000007d */
  Stealthcoin: 125,
  /** BRK | Breakout Coin | 0x8000007e */
  BreakoutCoin: 126,
  /** VC | Vcash | 0x8000007f */
  Vcash: 127,
  /** XMR | Monero | 0x80000080 */
  Monero: 128,
  /** VOX | Voxels | 0x80000081 */
  Voxels: 129,
  /** NAV | NavCoin | 0x80000082 */
  Navcoin: 130,
  /** FCT | Factom Factoids | 0x80000083 */
  FactomFactoids: 131,
  /** EC | Factom Entry Credits | 0x80000084 */
  FactomEntryCredits: 132,
  /** ZEC | Zcash | 0x80000085 */
  Zcash: 133,
  /** LSK | Lisk | 0x80000086 */
  Lisk: 134,
  /** STEEM | Steem | 0x80000087 */
  Steem: 135,
  /** XZC | ZCoin | 0x80000088 */
  Zcoin: 136,
  /** RBTC | Rootstock | 0x80000089 */
  Rootstock: 137,
  /** - | Giftblock | 0x8000008a */
  Giftblock: 138,
  /** RPT | RealPointCoin | 0x8000008b */
  Realpointcoin: 139,
  /** LBC | LBRY Credits | 0x8000008c */
  LbryCredits: 140,
  /** KMD | Komodo | 0x8000008d */
  Komodo: 141,
  /** BSQ | bisq Token | 0x8000008e */
  BisqToken: 142,
  /** RIC | Riecoin | 0x8000008f */
  Riecoin: 143,
  /** XRP | XRP | 0x80000090 */
  Xrp: 144,
  /** BCH | Bitcoin Cash | 0x80000091 */
  BitcoinCash: 145,
  /** NEBL | Neblio | 0x80000092 */
  Neblio: 146,
  /** ZCL | ZClassic | 0x80000093 */
  Zclassic: 147,
  /** XLM | Stellar Lumens | 0x80000094 */
  StellarLumens: 148,
  /** NLC2 | NoLimitCoin2 | 0x80000095 */
  Nolimitcoin2: 149,
  /** WHL | WhaleCoin | 0x80000096 */
  Whalecoin: 150,
  /** ERC | EuropeCoin | 0x80000097 */
  Europecoin: 151,
  /** DMD | Diamond | 0x80000098 */
  Diamond: 152,
  /** BTM | Bytom | 0x80000099 */
  Bytom: 153,
  /** BIO | Biocoin | 0x8000009a */
  Biocoin: 154,
  /** XWCC | Whitecoin Classic | 0x8000009b */
  WhitecoinClassic: 155,
  /** BTG | Bitcoin Gold | 0x8000009c */
  BitcoinGold: 156,
  /** BTC2X | Bitcoin 2x | 0x8000009d */
  Bitcoin2x: 157,
  /** SSN | SuperSkynet | 0x8000009e */
  Superskynet: 158,
  /** TOA | TOACoin | 0x8000009f */
  Toacoin: 159,
  /** BTX | Bitcore | 0x800000a0 */
  Bitcore: 160,
  /** ACC | Adcoin | 0x800000a1 */
  Adcoin: 161,
  /** BCO | Bridgecoin | 0x800000a2 */
  Bridgecoin: 162,
  /** ELLA | Ellaism | 0x800000a3 */
  Ellaism: 163,
  /** PIRL | Pirl | 0x800000a4 */
  Pirl: 164,
  /** XNO | Nano | 0x800000a5 */
  Nano: 165,
  /** VIVO | Vivo | 0x800000a6 */
  Vivo: 166,
  /** FRST | Firstcoin | 0x800000a7 */
  Firstcoin: 167,
  /** HNC | Helleniccoin | 0x800000a8 */
  Helleniccoin: 168,
  /** BUZZ | BUZZ | 0x800000a9 */
  Buzz: 169,
  /** MBRS | Ember | 0x800000aa */
  Ember: 170,
  /** HC | Hcash | 0x800000ab */
  Hcash: 171,
  /** HTML | HTMLCOIN | 0x800000ac */
  Htmlcoin: 172,
  /** ODN | Obsidian | 0x800000ad */
  Obsidian: 173,
  /** ONX | OnixCoin | 0x800000ae */
  Onixcoin: 174,
  /** RVN | Ravencoin | 0x800000af */
  Ravencoin: 175,
  /** GBX | GoByte | 0x800000b0 */
  Gobyte: 176,
  /** BTCZ | BitcoinZ | 0x800000b1 */
  Bitcoinz: 177,
  /** POA | Poa | 0x800000b2 */
  Poa: 178,
  /** NYC | NewYorkCoin | 0x800000b3 */
  Newyorkcoin: 179,
  /** MXT | MarteXcoin | 0x800000b4 */
  Martexcoin: 180,
  /** WC | Wincoin | 0x800000b5 */
  Wincoin: 181,
  /** MNX | Minexcoin | 0x800000b6 */
  Minexcoin: 182,
  /** BTCP | Bitcoin Private | 0x800000b7 */
  BitcoinPrivate: 183,
  /** MUSIC | Musicoin | 0x800000b8 */
  Musicoin: 184,
  /** BCA | Bitcoin Atom | 0x800000b9 */
  BitcoinAtom: 185,
  /** CRAVE | Crave | 0x800000ba */
  Crave: 186,
  /** STAK | STRAKS | 0x800000bb */
  Straks: 187,
  /** WBTC | World Bitcoin | 0x800000bc */
  WorldBitcoin: 188,
  /** LCH | LiteCash | 0x800000bd */
  Litecash: 189,
  /** EXCL | ExclusiveCoin | 0x800000be */
  Exclusivecoin: 190,
  /** LYNX | Lynx | 0x800000bf */
  Lynx: 191,
  /** LCC | LitecoinCash | 0x800000c0 */
  Litecoincash: 192,
  /** XFE | Feirm | 0x800000c1 */
  Feirm: 193,
  /** EOS | EOS | 0x800000c2 */
  Eos: 194,
  /** TRX | Tron | 0x800000c3 */
  Tron: 195,
  /** KOBO | Kobocoin | 0x800000c4 */
  Kobocoin: 196,
  /** HUSH | HUSH | 0x800000c5 */
  Hush: 197,
  /** BAN | Banano | 0x800000c6 */
  Banano: 198,
  /** ETF | ETF | 0x800000c7 */
  Etf: 199,
  /** OMNI | Omni | 0x800000c8 */
  Omni: 200,
  /** BIFI | BitcoinFile | 0x800000c9 */
  Bitcoinfile: 201,
  /** UFO | Uniform Fiscal Object | 0x800000ca */
  UniformFiscalObject: 202,
  /** CNMC | Cryptonodes | 0x800000cb */
  Cryptonodes: 203,
  /** BCN | Bytecoin | 0x800000cc */
  Bytecoin: 204,
  /** RIN | Ringo | 0x800000cd */
  Ringo: 205,
  /** ATP | Alaya | 0x800000ce */
  Alaya: 206,
  /** EVT | everiToken | 0x800000cf */
  Everitoken: 207,
  /** ATN | ATN | 0x800000d0 */
  Atn: 208,
  /** BIS | Bismuth | 0x800000d1 */
  Bismuth: 209,
  /** NEET | NEETCOIN | 0x800000d2 */
  Neetcoin: 210,
  /** BOPO | BopoChain | 0x800000d3 */
  Bopochain: 211,
  /** OOT | Utrum | 0x800000d4 */
  Utrum: 212,
  /** ALIAS | Alias | 0x800000d5 */
  Alias: 213,
  /** MONK | Monkey Project | 0x800000d6 */
  MonkeyProject: 214,
  /** BOXY | BoxyCoin | 0x800000d7 */
  Boxycoin: 215,
  /** FLO | Flo | 0x800000d8 */
  Flo: 216,
  /** MEC | Megacoin | 0x800000d9 */
  Megacoin: 217,
  /** BTDX | BitCloud | 0x800000da */
  Bitcloud: 218,
  /** XAX | Artax | 0x800000db */
  Artax: 219,
  /** ANON | ANON | 0x800000dc */
  Anon: 220,
  /** LTZ | LitecoinZ | 0x800000dd */
  Litecoinz: 221,
  /** BITG | Bitcoin Green | 0x800000de */
  BitcoinGreen: 222,
  /** ICP | Internet Computer (DFINITY) | 0x800000df */
  InternetComputerDfinity: 223,
  /** SMART | Smartcash | 0x800000e0 */
  Smartcash: 224,
  /** XUEZ | XUEZ | 0x800000e1 */
  Xuez: 225,
  /** HLM | Helium | 0x800000e2 */
  Helium: 226,
  /** WEB | Webchain | 0x800000e3 */
  Webchain: 227,
  /** ACM | Actinium | 0x800000e4 */
  Actinium: 228,
  /** NOS | NOS Stable Coins | 0x800000e5 */
  NosStableCoins: 229,
  /** BITC | BitCash | 0x800000e6 */
  Bitcash: 230,
  /** HTH | Help The Homeless Coin | 0x800000e7 */
  HelpTheHomelessCoin: 231,
  /** TZC | Trezarcoin | 0x800000e8 */
  Trezarcoin: 232,
  /** VAR | Varda | 0x800000e9 */
  Varda: 233,
  /** IOV | IOV | 0x800000ea */
  Iov: 234,
  /** FIO | FIO | 0x800000eb */
  Fio: 235,
  /** BSV | BitcoinSV | 0x800000ec */
  Bitcoinsv: 236,
  /** DXN | DEXON | 0x800000ed */
  Dexon: 237,
  /** QRL | Quantum Resistant Ledger | 0x800000ee */
  QuantumResistantLedger: 238,
  /** PCX | ChainX | 0x800000ef */
  Chainx: 239,
  /** LOKI | Loki | 0x800000f0 */
  Loki: 240,
  /** - | Imagewallet | 0x800000f1 */
  Imagewallet: 241,
  /** NIM | Nimiq | 0x800000f2 */
  Nimiq: 242,
  /** SOV | Sovereign Coin | 0x800000f3 */
  SovereignCoin: 243,
  /** JCT | Jibital Coin | 0x800000f4 */
  JibitalCoin: 244,
  /** SLP | Simple Ledger Protocol | 0x800000f5 */
  SimpleLedgerProtocol: 245,
  /** EWT | Energy Web | 0x800000f6 */
  EnergyWeb: 246,
  /** UC | Ulord | 0x800000f7 */
  Ulord: 247,
  /** EXOS | EXOS | 0x800000f8 */
  Exos: 248,
  /** ECA | Electra | 0x800000f9 */
  Electra: 249,
  /** SOOM | Soom | 0x800000fa */
  Soom: 250,
  /** XRD | Redstone | 0x800000fb */
  Redstone: 251,
  /** FREE | FreeCoin | 0x800000fc */
  Freecoin: 252,
  /** NPW | NewPowerCoin | 0x800000fd */
  Newpowercoin: 253,
  /** BST | BlockStamp | 0x800000fe */
  Blockstamp: 254,
  /** - | SmartHoldem | 0x800000ff */
  Smartholdem: 255,
  /** NANO | Bitcoin Nano | 0x80000100 */
  BitcoinNano: 256,
  /** BTCC | Bitcoin Core | 0x80000101 */
  BitcoinCore: 257,
  /** - | Zen Protocol | 0x80000102 */
  ZenProtocol: 258,
  /** ZEST | Zest | 0x80000103 */
  Zest: 259,
  /** ABT | ArcBlock | 0x80000104 */
  Arcblock: 260,
  /** PION | Pion | 0x80000105 */
  Pion: 261,
  /** DT3 | DreamTeam3 | 0x80000106 */
  Dreamteam3: 262,
  /** ZBUX | Zbux | 0x80000107 */
  Zbux: 263,
  /** KPL | Kepler | 0x80000108 */
  Kepler: 264,
  /** TPAY | TokenPay | 0x80000109 */
  Tokenpay: 265,
  /** ZILLA | ChainZilla | 0x8000010a */
  Chainzilla: 266,
  /** ANK | Anker | 0x8000010b */
  Anker: 267,
  /** BCC | BCChain | 0x8000010c */
  Bcchain: 268,
  /** HPB | HPB | 0x8000010d */
  Hpb: 269,
  /** ONE | ONE | 0x8000010e */
  One: 270,
  /** SBC | SBC | 0x8000010f */
  Sbc: 271,
  /** IPC | IPChain | 0x80000110 */
  Ipchain: 272,
  /** DMTC | Dominantchain | 0x80000111 */
  Dominantchain: 273,
  /** OGC | Onegram | 0x80000112 */
  Onegram: 274,
  /** SHIT | Shitcoin | 0x80000113 */
  Shitcoin: 275,
  /** ANDES | Andescoin | 0x80000114 */
  Andescoin: 276,
  /** AREPA | Arepacoin | 0x80000115 */
  Arepacoin: 277,
  /** BOLI | Bolivarcoin | 0x80000116 */
  Bolivarcoin: 278,
  /** RIL | Rilcoin | 0x80000117 */
  Rilcoin: 279,
  /** HTR | Hathor Network | 0x80000118 */
  HathorNetwork: 280,
  /** ACME | Accumulate | 0x80000119 */
  Accumulate: 281,
  /** BRAVO | BRAVO | 0x8000011a */
  Bravo: 282,
  /** ALGO | Algorand | 0x8000011b */
  Algorand: 283,
  /** BZX | Bitcoinzero | 0x8000011c */
  Bitcoinzero: 284,
  /** GXX | GravityCoin | 0x8000011d */
  Gravitycoin: 285,
  /** HEAT | HEAT | 0x8000011e */
  Heat: 286,
  /** XDN | DigitalNote | 0x8000011f */
  Digitalnote: 287,
  /** FSN | FUSION | 0x80000120 */
  Fusion: 288,
  /** CPC | Capricoin | 0x80000121 */
  Capricoin: 289,
  /** BOLD | Bold | 0x80000122 */
  Bold: 290,
  /** IOST | IOST | 0x80000123 */
  Iost: 291,
  /** TKEY | Tkeycoin | 0x80000124 */
  Tkeycoin: 292,
  /** USE | Usechain | 0x80000125 */
  Usechain: 293,
  /** BCZ | BitcoinCZ | 0x80000126 */
  Bitcoincz: 294,
  /** IOC | Iocoin | 0x80000127 */
  Iocoin: 295,
  /** ASF | Asofe | 0x80000128 */
  Asofe: 296,
  /** MASS | MASS | 0x80000129 */
  Mass: 297,
  /** FAIR | FairCoin | 0x8000012a */
  Faircoin: 298,
  /** NUKO | Nekonium | 0x8000012b */
  Nekonium: 299,
  /** GNX | Genaro Network | 0x8000012c */
  GenaroNetwork: 300,
  /** DIVI | Divi Project | 0x8000012d */
  DiviProject: 301,
  /** CMT | Community | 0x8000012e */
  Community: 302,
  /** EUNO | EUNO | 0x8000012f */
  Euno: 303,
  /** IOTX | IoTeX | 0x80000130 */
  Iotex: 304,
  /** ONION | DeepOnion | 0x80000131 */
  Deeponion: 305,
  /** 8BIT | 8Bit | 0x80000132 */
  Coin8bit: 306,
  /** ATC | AToken Coin | 0x80000133 */
  AtokenCoin: 307,
  /** BTS | Bitshares | 0x80000134 */
  Bitshares: 308,
  /** CKB | Nervos CKB | 0x80000135 */
  NervosCkb: 309,
  /** UGAS | Ultrain | 0x80000136 */
  Ultrain: 310,
  /** ADS | Adshares | 0x80000137 */
  Adshares: 311,
  /** ARA | Aura | 0x80000138 */
  Aura: 312,
  /** ZIL | Zilliqa | 0x80000139 */
  Zilliqa: 313,
  /** MOAC | MOAC | 0x8000013a */
  Moac: 314,
  /** SWTC | SWTC | 0x8000013b */
  Swtc: 315,
  /** VNSC | vnscoin | 0x8000013c */
  Vnscoin: 316,
  /** PLUG | Pl^g | 0x8000013d */
  PlG: 317,
  /** MAN | Matrix AI Network | 0x8000013e */
  MatrixAiNetwork: 318,
  /** ECC | ECCoin | 0x8000013f */
  Eccoin: 319,
  /** RPD | Rapids | 0x80000140 */
  Rapids: 320,
  /** RAP | Rapture | 0x80000141 */
  Rapture: 321,
  /** GARD | Hashgard | 0x80000142 */
  Hashgard: 322,
  /** ZER | Zero | 0x80000143 */
  Zero: 323,
  /** EBST | eBoost | 0x80000144 */
  Eboost: 324,
  /** SHARD | Shard | 0x80000145 */
  Shard: 325,
  /** MRX | Metrix Coin | 0x80000146 */
  MetrixCoin: 326,
  /** CMM | Commercium | 0x80000147 */
  Commercium: 327,
  /** BLOCK | Blocknet | 0x80000148 */
  Blocknet: 328,
  /** AUDAX | AUDAX | 0x80000149 */
  Audax: 329,
  /** LUNA | Terra | 0x8000014a */
  Terra: 330,
  /** ZPM | zPrime | 0x8000014b */
  Zprime: 331,
  /** KUVA | Kuva Utility Note | 0x8000014c */
  KuvaUtilityNote: 332,
  /** MEM | MemCoin | 0x8000014d */
  Memcoin: 333,
  /** CS | Credits | 0x8000014e */
  Credits: 334,
  /** SWIFT | SwiftCash | 0x8000014f */
  Swiftcash: 335,
  /** FIX | FIX | 0x80000150 */
  Fix: 336,
  /** CPC | CPChain | 0x80000151 */
  Cpchain: 337,
  /** VGO | VirtualGoodsToken | 0x80000152 */
  Virtualgoodstoken: 338,
  /** DVT | DeVault | 0x80000153 */
  Devault: 339,
  /** N8V | N8VCoin | 0x80000154 */
  N8vcoin: 340,
  /** MTNS | OmotenashiCoin | 0x80000155 */
  Omotenashicoin: 341,
  /** BLAST | BLAST | 0x80000156 */
  Blast: 342,
  /** DCT | DECENT | 0x80000157 */
  Decent: 343,
  /** AUX | Auxilium | 0x80000158 */
  Auxilium: 344,
  /** USDP | USDP | 0x80000159 */
  Usdp: 345,
  /** HTDF | HTDF | 0x8000015a */
  Htdf: 346,
  /** YEC | Ycash | 0x8000015b */
  Ycash: 347,
  /** QLC | QLC Chain | 0x8000015c */
  QlcChain: 348,
  /** TEA | Icetea Blockchain | 0x8000015d */
  IceteaBlockchain: 349,
  /** ARW | ArrowChain | 0x8000015e */
  Arrowchain: 350,
  /** MDM | Medium | 0x8000015f */
  Medium: 351,
  /** CYB | Cybex | 0x80000160 */
  Cybex: 352,
  /** LTO | LTO Network | 0x80000161 */
  LtoNetwork: 353,
  /** DOT | Polkadot | 0x80000162 */
  Polkadot: 354,
  /** AEON | Aeon | 0x80000163 */
  Aeon: 355,
  /** RES | Resistance | 0x80000164 */
  Resistance: 356,
  /** AYA | Aryacoin | 0x80000165 */
  Aryacoin: 357,
  /** DAPS | Dapscoin | 0x80000166 */
  Dapscoin: 358,
  /** CSC | CasinoCoin | 0x80000167 */
  Casinocoin: 359,
  /** VSYS | V Systems | 0x80000168 */
  VSystems: 360,
  /** NOLLAR | Nollar | 0x80000169 */
  Nollar: 361,
  /** XNOS | NOS | 0x8000016a */
  Nos: 362,
  /** CPU | CPUchain | 0x8000016b */
  Cpuchain: 363,
  /** LAMB | Lambda Storage Chain | 0x8000016c */
  LambdaStorageChain: 364,
  /** VCT | ValueCyber | 0x8000016d */
  Valuecyber: 365,
  /** CZR | Canonchain | 0x8000016e */
  Canonchain: 366,
  /** ABBC | ABBC | 0x8000016f */
  Abbc: 367,
  /** HET | HET | 0x80000170 */
  Het: 368,
  /** XAS | Asch | 0x80000171 */
  Asch: 369,
  /** VDL | Vidulum | 0x80000172 */
  Vidulum: 370,
  /** MED | MediBloc | 0x80000173 */
  Medibloc: 371,
  /** ZVC | ZVChain | 0x80000174 */
  Zvchain: 372,
  /** VESTX | Vestx | 0x80000175 */
  Vestx: 373,
  /** DBT | DarkBit | 0x80000176 */
  Darkbit: 374,
  /** SEOS | SuperEOS | 0x80000177 */
  Supereos: 375,
  /** MXW | Maxonrow | 0x80000178 */
  Maxonrow: 376,
  /** ZNZ | ZENZO | 0x80000179 */
  Zenzo: 377,
  /** XCX | XChain | 0x8000017a */
  Xchain: 378,
  /** SOX | SonicX | 0x8000017b */
  Sonicx: 379,
  /** NYZO | Nyzo | 0x8000017c */
  Nyzo: 380,
  /** ULC | ULCoin | 0x8000017d */
  Ulcoin: 381,
  /** RYO | Ryo Currency | 0x8000017e */
  RyoCurrency: 382,
  /** KAL | Kaleidochain | 0x8000017f */
  Kaleidochain: 383,
  /** XSN | Stakenet | 0x80000180 */
  Stakenet: 384,
  /** DOGEC | DogeCash | 0x80000181 */
  Dogecash: 385,
  /** BMV | Bitcoin Matteo's Vision | 0x80000182 */
  BitcoinMatteoSVision: 386,
  /** QBC | Quebecoin | 0x80000183 */
  Quebecoin: 387,
  /** IMG | ImageCoin | 0x80000184 */
  Imagecoin: 388,
  /** QOS | QOS | 0x80000185 */
  Qos: 389,
  /** PKT | PKT | 0x80000186 */
  Pkt: 390,
  /** LHD | LitecoinHD | 0x80000187 */
  Litecoinhd: 391,
  /** CENNZ | CENNZnet | 0x80000188 */
  Cennznet: 392,
  /** HSN | Hyper Speed Network | 0x80000189 */
  HyperSpeedNetwork: 393,
  /** CRO | Crypto Chain | 0x8000018a */
  CryptoChain: 394,
  /** UMBRU | Umbru | 0x8000018b */
  Umbru: 395,
  /** EVER | Everscale | 0x8000018c */
  Everscale: 396,
  /** NEAR | NEAR Protocol | 0x8000018d */
  NearProtocol: 397,
  /** XPC | XPChain | 0x8000018e */
  Xpchain: 398,
  /** ZOC | 01coin | 0x8000018f */
  Coin01coin: 399,
  /** NIX | NIX | 0x80000190 */
  Nix: 400,
  /** UC | Utopiacoin | 0x80000191 */
  Utopiacoin: 401,
  /** GALI | Galilel | 0x80000192 */
  Galilel: 402,
  /** OLT | Oneledger | 0x80000193 */
  Oneledger: 403,
  /** XBI | XBI | 0x80000194 */
  Xbi: 404,
  /** DONU | DONU | 0x80000195 */
  Donu: 405,
  /** EARTHS | Earths | 0x80000196 */
  Earths: 406,
  /** HDD | HDDCash | 0x80000197 */
  Hddcash: 407,
  /** SUGAR | Sugarchain | 0x80000198 */
  Sugarchain: 408,
  /** AILE | AileCoin | 0x80000199 */
  Ailecoin: 409,
  /** TENT | TENT | 0x8000019a */
  Tent: 410,
  /** TAN | Tangerine Network | 0x8000019b */
  TangerineNetwork: 411,
  /** AIN | AIN | 0x8000019c */
  Ain: 412,
  /** MSR | Masari | 0x8000019d */
  Masari: 413,
  /** SUMO | Sumokoin | 0x8000019e */
  Sumokoin: 414,
  /** ETN | Electroneum | 0x8000019f */
  Electroneum: 415,
  /** BYTZ | BYTZ | 0x800001a0 */
  Bytz: 416,
  /** WOW | Wownero | 0x800001a1 */
  Wownero: 417,
  /** XTNC | XtendCash | 0x800001a2 */
  Xtendcash: 418,
  /** LTHN | Lethean | 0x800001a3 */
  Lethean: 419,
  /** NODE | NodeHost | 0x800001a4 */
  Nodehost: 420,
  /** AGM | Argoneum | 0x800001a5 */
  Argoneum: 421,
  /** CCX | Conceal Network | 0x800001a6 */
  ConcealNetwork: 422,
  /** TNET | Title Network | 0x800001a7 */
  TitleNetwork: 423,
  /** TELOS | TelosCoin | 0x800001a8 */
  Teloscoin: 424,
  /** AION | Aion | 0x800001a9 */
  Aion: 425,
  /** BC | Bitcoin Confidential | 0x800001aa */
  BitcoinConfidential: 426,
  /** KTV | KmushiCoin | 0x800001ab */
  Kmushicoin: 427,
  /** ZCR | ZCore | 0x800001ac */
  Zcore: 428,
  /** ERG | Ergo | 0x800001ad */
  Ergo: 429,
  /** PESO | Criptopeso | 0x800001ae */
  Criptopeso: 430,
  /** BTC2 | Bitcoin 2 | 0x800001af */
  Bitcoin2: 431,
  /** XRPHD | XRPHD | 0x800001b0 */
  Xrphd: 432,
  /** WE | WE Coin | 0x800001b1 */
  WeCoin: 433,
  /** KSM | Kusama | 0x800001b2 */
  Kusama: 434,
  /** PCN | Peepcoin | 0x800001b3 */
  Peepcoin: 435,
  /** NCH | NetCloth | 0x800001b4 */
  Netcloth: 436,
  /** ICU | CHIPO | 0x800001b5 */
  Chipo: 437,
  /** FNSA | FINSCHIA | 0x800001b6 */
  Finschia: 438,
  /** DTP | DeVault Token Protocol | 0x800001b7 */
  DevaultTokenProtocol: 439,
  /** BTCR | Bitcoin Royale | 0x800001b8 */
  BitcoinRoyale: 440,
  /** AERGO | AERGO | 0x800001b9 */
  Aergo: 441,
  /** XTH | Dothereum | 0x800001ba */
  Dothereum: 442,
  /** LV | Lava | 0x800001bb */
  Lava: 443,
  /** PHR | Phore | 0x800001bc */
  Phore: 444,
  /** VITAE | Vitae | 0x800001bd */
  Vitae: 445,
  /** COCOS | Cocos-BCX | 0x800001be */
  CocosBcx: 446,
  /** DIN | Dinero | 0x800001bf */
  Dinero: 447,
  /** SPL | Simplicity | 0x800001c0 */
  Simplicity: 448,
  /** YCE | MYCE | 0x800001c1 */
  Myce: 449,
  /** XLR | Solaris | 0x800001c2 */
  Solaris: 450,
  /** KTS | Klimatas | 0x800001c3 */
  Klimatas: 451,
  /** DGLD | DGLD | 0x800001c4 */
  Dgld: 452,
  /** XNS | Insolar | 0x800001c5 */
  Insolar: 453,
  /** EM | EMPOW | 0x800001c6 */
  Empow: 454,
  /** SHN | ShineBlocks | 0x800001c7 */
  Shineblocks: 455,
  /** SEELE | Seele | 0x800001c8 */
  Seele: 456,
  /** AE | æternity | 0x800001c9 */
  Ternity: 457,
  /** ODX | ObsidianX | 0x800001ca */
  Obsidianx: 458,
  /** KAVA | Kava | 0x800001cb */
  Kava: 459,
  /** GLEEC | GLEEC | 0x800001cc */
  Gleec: 460,
  /** FIL | Filecoin | 0x800001cd */
  Filecoin: 461,
  /** RUTA | Rutanio | 0x800001ce */
  Rutanio: 462,
  /** CSDT | CSDT | 0x800001cf */
  Csdt: 463,
  /** ETI | EtherInc | 0x800001d0 */
  Etherinc: 464,
  /** ZSLP | Zclassic Simple Ledger Protocol | 0x800001d1 */
  ZclassicSimpleLedgerProtocol: 465,
  /** ERE | EtherCore | 0x800001d2 */
  Ethercore: 466,
  /** DX | DxChain Token | 0x800001d3 */
  DxchainToken: 467,
  /** CPS | Capricoin+ | 0x800001d4 */
  Capricoin468: 468,
  /** BTH | Bithereum | 0x800001d5 */
  Bithereum: 469,
  /** MESG | MESG | 0x800001d6 */
  Mesg: 470,
  /** FIMK | FIMK | 0x800001d7 */
  Fimk: 471,
  /** AR | Arweave | 0x800001d8 */
  Arweave: 472,
  /** OGO | Origo | 0x800001d9 */
  Origo: 473,
  /** ROSE | Oasis Network | 0x800001da */
  OasisNetwork: 474,
  /** BARE | BARE Network | 0x800001db */
  BareNetwork: 475,
  /** GLEEC | GleecBTC | 0x800001dc */
  Gleecbtc: 476,
  /** CLR | Color Coin | 0x800001dd */
  ColorCoin: 477,
  /** RNG | Ring | 0x800001de */
  Ring: 478,
  /** OLO | Tool Global | 0x800001df */
  ToolGlobal: 479,
  /** PEXA | Pexa | 0x800001e0 */
  Pexa: 480,
  /** MOON | Mooncoin | 0x800001e1 */
  Mooncoin: 481,
  /** OCEAN | Ocean Protocol | 0x800001e2 */
  OceanProtocol: 482,
  /** BNT | Bluzelle Native | 0x800001e3 */
  BluzelleNative: 483,
  /** AMO | AMO Blockchain | 0x800001e4 */
  AmoBlockchain: 484,
  /** FCH | FreeCash | 0x800001e5 */
  Freecash: 485,
  /** LAT | PlatON | 0x800001e6 */
  Platon: 486,
  /** COIN | Bitcoin Bank | 0x800001e7 */
  BitcoinBank: 487,
  /** VEO | Amoveo | 0x800001e8 */
  Amoveo: 488,
  /** CCA | Counos Coin | 0x800001e9 */
  CounosCoin: 489,
  /** GFN | Graphene | 0x800001ea */
  Graphene: 490,
  /** BIP | Minter Network | 0x800001eb */
  MinterNetwork: 491,
  /** KPG | Kunpeng Network | 0x800001ec */
  KunpengNetwork: 492,
  /** FIN | FINL Chain | 0x800001ed */
  FinlChain: 493,
  /** BAND | Band | 0x800001ee */
  Band: 494,
  /** DROP | Dropil | 0x800001ef */
  Dropil: 495,
  /** BHT | Bluehelix Chain | 0x800001f0 */
  BluehelixChain: 496,
  /** LYRA | Scrypta | 0x800001f1 */
  Scrypta: 497,
  /** CS | Credits | 0x800001f2 */
  Credits498: 498,
  /** RUPX | Rupaya | 0x800001f3 */
  Rupaya: 499,
  /** THETA | Theta | 0x800001f4 */
  Theta: 500,
  /** SOL | Solana | 0x800001f5 */
  Solana: 501,
  /** THT | ThoughtAI | 0x800001f6 */
  Thoughtai: 502,
  /** CFX | Conflux | 0x800001f7 */
  Conflux: 503,
  /** KUMA | Kumacoin | 0x800001f8 */
  Kumacoin: 504,
  /** HASH | Provenance | 0x800001f9 */
  Provenance: 505,
  /** CSPR | Casper | 0x800001fa */
  Casper: 506,
  /** EARTH | EARTH | 0x800001fb */
  Earth: 507,
  /** EGLD | MultiversX | 0x800001fc */
  Multiversx: 508,
  /** CHI | Xaya | 0x800001fd */
  Xaya: 509,
  /** KOTO | Koto | 0x800001fe */
  Koto: 510,
  /** OTC | θ | 0x800001ff */
  Otc: 511,
  /** RXD | Radiant | 0x80000200 */
  Radiant: 512,
  /** SEELEN | Seele-N | 0x80000201 */
  SeeleN: 513,
  /** AETH | AETH | 0x80000202 */
  Aeth: 514,
  /** DNA | Idena | 0x80000203 */
  Idena: 515,
  /** VEE | Virtual Economy Era | 0x80000204 */
  VirtualEconomyEra: 516,
  /** SIERRA | SierraCoin | 0x80000205 */
  Sierracoin: 517,
  /** LET | Linkeye | 0x80000206 */
  Linkeye: 518,
  /** BSC | Bitcoin Smart Contract | 0x80000207 */
  BitcoinSmartContract: 519,
  /** BTCV | BitcoinVIP | 0x80000208 */
  Bitcoinvip: 520,
  /** ABA | Dabacus | 0x80000209 */
  Dabacus: 521,
  /** SCC | StakeCubeCoin | 0x8000020a */
  Stakecubecoin: 522,
  /** EDG | Edgeware | 0x8000020b */
  Edgeware: 523,
  /** AMS | AmsterdamCoin | 0x8000020c */
  Amsterdamcoin: 524,
  /** GOSS | GOSSIP Coin | 0x8000020d */
  GossipCoin: 525,
  /** BU | BUMO | 0x8000020e */
  Bumo: 526,
  /** GRAM | GRAM | 0x8000020f */
  Gram: 527,
  /** YAP | Yapstone | 0x80000210 */
  Yapstone: 528,
  /** SCRT | Secret Network | 0x80000211 */
  SecretNetwork: 529,
  /** NOVO | Novo | 0x80000212 */
  Novo: 530,
  /** GHOST | Ghost | 0x80000213 */
  Ghost: 531,
  /** HST | HST | 0x80000214 */
  Hst: 532,
  /** PRJ | ProjectCoin | 0x80000215 */
  Projectcoin: 533,
  /** YOU | YOUChain | 0x80000216 */
  Youchain: 534,
  /** XHV | Haven Protocol | 0x80000217 */
  HavenProtocol: 535,
  /** BYND | Beyondcoin | 0x80000218 */
  Beyondcoin: 536,
  /** JOYS | Joys Digital | 0x80000219 */
  JoysDigital: 537,
  /** VAL | Valorbit | 0x8000021a */
  Valorbit: 538,
  /** FLOW | Flow | 0x8000021b */
  Flow: 539,
  /** SMESH | Spacemesh Coin | 0x8000021c */
  SpacemeshCoin: 540,
  /** SCDO | SCDO | 0x8000021d */
  Scdo: 541,
  /** IQS | IQ-Cash | 0x8000021e */
  IqCash: 542,
  /** BIND | Compendia | 0x8000021f */
  Compendia: 543,
  /** COINEVO | Coinevo | 0x80000220 */
  Coinevo: 544,
  /** SCRIBE | Scribe | 0x80000221 */
  Scribe: 545,
  /** HYN | Hyperion | 0x80000222 */
  Hyperion: 546,
  /** BHP | BHP | 0x80000223 */
  Bhp: 547,
  /** BBC | BigBang Core | 0x80000224 */
  BigbangCore: 548,
  /** MKF | MarketFinance | 0x80000225 */
  Marketfinance: 549,
  /** XDC | XinFin | 0x80000226 */
  Xinfin: 550,
  /** STR | Straightedge | 0x80000227 */
  Straightedge: 551,
  /** SUM | Sumcoin | 0x80000228 */
  Sumcoin: 552,
  /** HBC | HuobiChain | 0x80000229 */
  Huobichain: 553,
  /** --- | reserved | 0x8000022a */
  Coin554: 554,
  /** BCS | Bitcoin Smart | 0x8000022b */
  BitcoinSmart: 555,
  /** KTS | Kratos | 0x8000022c */
  Kratos: 556,
  /** LKR | Lkrcoin | 0x8000022d */
  Lkrcoin: 557,
  /** TAO | Tao | 0x8000022e */
  Tao: 558,
  /** XWC | Whitecoin | 0x8000022f */
  Whitecoin: 559,
  /** DEAL | DEAL | 0x80000230 */
  Deal: 560,
  /** NTY | Nexty | 0x80000231 */
  Nexty: 561,
  /** TOP | TOP NetWork | 0x80000232 */
  TopNetwork: 562,
  /** --- | reserved | 0x80000233 */
  Coin563: 563,
  /** AG | Agoric | 0x80000234 */
  Agoric: 564,
  /** CICO | Coinicles | 0x80000235 */
  Coinicles: 565,
  /** IRIS | Irisnet | 0x80000236 */
  Irisnet: 566,
  /** NCG | Nine Chronicles | 0x80000237 */
  NineChronicles: 567,
  /** LRG | Large Coin | 0x80000238 */
  LargeCoin: 568,
  /** SERO | Super Zero Protocol | 0x80000239 */
  SuperZeroProtocol: 569,
  /** BDX | Beldex | 0x8000023a */
  Beldex: 570,
  /** CCXX | Counos X | 0x8000023b */
  CounosX: 571,
  /** SLS | Saluscoin | 0x8000023c */
  Saluscoin: 572,
  /** SRM | Serum | 0x8000023d */
  Serum: 573,
  /** --- | reserved | 0x8000023e */
  Coin574: 574,
  /** VIVT | VIDT Datalink | 0x8000023f */
  VidtDatalink: 575,
  /** BPS | BitcoinPoS | 0x80000240 */
  Bitcoinpos: 576,
  /** NKN | NKN | 0x80000241 */
  Nkn: 577,
  /** ICL | ILCOIN | 0x80000242 */
  Ilcoin: 578,
  /** BONO | Bonorum | 0x80000243 */
  Bonorum: 579,
  /** PLC | PLATINCOIN | 0x80000244 */
  Platincoin: 580,
  /** DUN | Dune | 0x80000245 */
  Dune: 581,
  /** DMCH | Darmacash | 0x80000246 */
  Darmacash: 582,
  /** CTC | Creditcoin | 0x80000247 */
  Creditcoin: 583,
  /** KELP | Haidai Network | 0x80000248 */
  HaidaiNetwork: 584,
  /** GBCR | GoldBCR | 0x80000249 */
  Goldbcr: 585,
  /** XDAG | XDAG | 0x8000024a */
  Xdag: 586,
  /** PRV | Incognito Privacy | 0x8000024b */
  IncognitoPrivacy: 587,
  /** SCAP | SafeCapital | 0x8000024c */
  Safecapital: 588,
  /** TFUEL | Theta Fuel | 0x8000024d */
  ThetaFuel: 589,
  /** GTM | Gentarium | 0x8000024e */
  Gentarium: 590,
  /** RNL | RentalChain | 0x8000024f */
  Rentalchain: 591,
  /** GRIN | Grin | 0x80000250 */
  Grin: 592,
  /** MWC | MimbleWimbleCoin | 0x80000251 */
  Mimblewimblecoin: 593,
  /** DOCK | Dock | 0x80000252 */
  Dock: 594,
  /** POLYX | Polymesh | 0x80000253 */
  Polymesh: 595,
  /** DIVER | Divergenti | 0x80000254 */
  Divergenti: 596,
  /** XEP | Electra Protocol | 0x80000255 */
  ElectraProtocol: 597,
  /** APN | Apron | 0x80000256 */
  Apron: 598,
  /** TFC | Turbo File Coin | 0x80000257 */
  TurboFileCoin: 599,
  /** UTE | Unit-e | 0x80000258 */
  UnitE: 600,
  /** MTC | Metacoin | 0x80000259 */
  Metacoin: 601,
  /** NC | NobodyCash | 0x8000025a */
  Nobodycash: 602,
  /** XINY | Xinyuehu | 0x8000025b */
  Xinyuehu: 603,
  /** DYN | Dynamo | 0x8000025c */
  Dynamo: 604,
  /** BUFS | Buffer | 0x8000025d */
  Buffer: 605,
  /** STOS | Stratos | 0x8000025e */
  Stratos: 606,
  /** TON | TON | 0x8000025f */
  Ton: 607,
  /** TAFT | TAFT | 0x80000260 */
  Taft: 608,
  /** HYDRA | HYDRA | 0x80000261 */
  Hydra: 609,
  /** NOR | Noir | 0x80000262 */
  Noir: 610,
  /** - | Manta Network Private Asset | 0x80000263 */
  MantaNetworkPrivateAsset: 611,
  /** - | Calamari Network Private Asset | 0x80000264 */
  CalamariNetworkPrivateAsset: 612,
  /** WCN | Widecoin | 0x80000265 */
  Widecoin: 613,
  /** OPT | Optimistic Ethereum | 0x80000266 */
  OptimisticEthereum: 614,
  /** PSWAP | PolkaSwap | 0x80000267 */
  Polkaswap: 615,
  /** VAL | Validator | 0x80000268 */
  Validator: 616,
  /** XOR | Sora | 0x80000269 */
  Sora: 617,
  /** SSP | SmartShare | 0x8000026a */
  Smartshare: 618,
  /** DEI | DeimosX | 0x8000026b */
  Deimosx: 619,
  /** --- | reserved | 0x8000026c */
  Coin620: 620,
  /** ZERO | Singularity | 0x8000026d */
  Singularity: 621,
  /** ALPHA | AlphaDAO | 0x8000026e */
  Alphadao: 622,
  /** BDECO | BDCashProtocol Ecosystem | 0x8000026f */
  BdcashprotocolEcosystem: 623,
  /** NOBL | Nobility | 0x80000270 */
  Nobility: 624,
  /** EAST | Eastcoin | 0x80000271 */
  Eastcoin: 625,
  /** KDA | Kadena | 0x80000272 */
  Kadena: 626,
  /** SOUL | Phantasma | 0x80000273 */
  Phantasma: 627,
  /** LORE | Gitopia | 0x80000274 */
  Gitopia: 628,
  /** FNR | Fincor | 0x80000275 */
  Fincor: 629,
  /** NEXUS | Nexus | 0x80000276 */
  Nexus630: 630,
  /** QTZ | Quartz | 0x80000277 */
  Quartz: 631,
  /** MAS | Massa | 0x80000278 */
  Massa: 632,
  /** CALL | Callchain | 0x80000279 */
  Callchain: 633,
  /** VAL | Validity | 0x8000027a */
  Validity: 634,
  /** POKT | Pocket Network | 0x8000027b */
  PocketNetwork: 635,
  /** EMIT | EMIT | 0x8000027c */
  Emit: 636,
  /** APTOS | Aptos | 0x8000027d */
  Aptos: 637,
  /** ADON | ADON | 0x8000027e */
  Adon: 638,
  /** BTSG | BitSong | 0x8000027f */
  Bitsong: 639,
  /** LFC | Leofcoin | 0x80000280 */
  Leofcoin: 640,
  /** KCS | KuCoin Shares | 0x80000281 */
  KucoinShares: 641,
  /** KCC | KuCoin Community Chain | 0x80000282 */
  KucoinCommunityChain: 642,
  /** AZERO | Aleph Zero | 0x80000283 */
  AlephZero: 643,
  /** TREE | Tree | 0x80000284 */
  Tree: 644,
  /** LX | Lynx | 0x80000285 */
  Lynx645: 645,
  /** XLN | Lunarium | 0x80000286 */
  Lunarium: 646,
  /** CIC | CIC Chain | 0x80000287 */
  CicChain: 647,
  /** ZRB | Zarb | 0x80000288 */
  Zarb: 648,
  /** --- | reserved | 0x80000289 */
  Coin649: 649,
  /** UCO | Archethic | 0x8000028a */
  Archethic: 650,
  /** SFX | Safex Cash | 0x8000028b */
  SafexCash: 651,
  /** SFT | Safex Token | 0x8000028c */
  SafexToken: 652,
  /** WSFX | Wrapped Safex Cash | 0x8000028d */
  WrappedSafexCash: 653,
  /** USDG | US Digital Gold | 0x8000028e */
  UsDigitalGold: 654,
  /** WMP | WAMP | 0x8000028f */
  Wamp: 655,
  /** EKTA | Ekta | 0x80000290 */
  Ekta: 656,
  /** YDA | YadaCoin | 0x80000291 */
  Yadacoin: 657,
  /** WHIVE | Whive | 0x80000292 */
  Whive: 658,
  /** KOIN | Koinos | 0x80000293 */
  Koinos: 659,
  /** PIRATE | PirateCash | 0x80000294 */
  Piratecash: 660,
  /** UNQ | Unique | 0x80000295 */
  Unique: 661,
  /** ULM | UltonSmartchain | 0x80000296 */
  Ultonsmartchain: 662,
  /** SFRX | EtherGem Sapphire | 0x80000297 */
  EthergemSapphire: 663,
  /** BSTY | GlobalBoost-Y | 0x80000298 */
  GlobalboostY: 664,
  /** IMP | Impact Protocol | 0x80000299 */
  ImpactProtocol: 665,
  /** ACT | Achain | 0x8000029a */
  Achain: 666,
  /** PRKL | Perkle | 0x8000029b */
  Perkle: 667,
  /** SSC | SelfSell | 0x8000029c */
  Selfsell: 668,
  /** GC | GateChain | 0x8000029d */
  Gatechain: 669,
  /** PLGR | Pledger | 0x8000029e */
  Pledger: 670,
  /** MPLGR | Pledger | 0x8000029f */
  Pledger671: 671,
  /** KNOX | Knox | 0x800002a0 */
  Knox: 672,
  /** ZED | ZED | 0x800002a1 */
  Zed: 673,
  /** CNDL | Candle | 0x800002a2 */
  Candle: 674,
  /** WLKR | Walker Crypto Innovation Index | 0x800002a3 */
  WalkerCryptoInnovationIndex: 675,
  /** WLKRR | Walker | 0x800002a4 */
  Walker: 676,
  /** YUNGE | Yunge | 0x800002a5 */
  Yunge: 677,
  /** Voken | Voken | 0x800002a6 */
  Voken: 678,
  /** APL | Apollo | 0x800002a7 */
  Apollo: 679,
  /** Evrynet | Evrynet | 0x800002a8 */
  Evrynet: 680,
  /** NENG | Nengcoin | 0x800002a9 */
  Nengcoin: 681,
  /** CHTA | Cheetahcoin | 0x800002aa */
  Cheetahcoin: 682,
  /** ALEO | Aleo Network | 0x800002ab */
  AleoNetwork: 683,
  /** HMS | Hemis | 0x800002ac */
  Hemis: 684,
  /** OAS | Oasys | 0x800002ad */
  Oasys: 685,
  /** KAR | Karura Network | 0x800002ae */
  KaruraNetwork: 686,
  /** FLON | FullOn Network | 0x800002af */
  FullonNetwork: 687,
  /** CET | CoinEx Chain | 0x800002b0 */
  CoinexChain: 688,
  /** XLINK | XLink Chain | 0x800002b1 */
  XlinkChain: 689,
  /** KLV | KleverChain | 0x800002b2 */
  Kleverchain: 690,
  /** TNT | Tangle | 0x800002b3 */
  Tangle: 691,
  /** GTG | Gotigin | 0x800002b4 */
  Gotigin: 692,
  /** NET | RealityNet | 0x800002b5 */
  Realitynet: 693,
  /** VTBC | VTB Community | 0x800002b6 */
  VtbCommunity: 694,
  /** DIONE | Odyssey Chain | 0x800002b7 */
  OdysseyChain: 695,
  /** LUM | Lumos | 0x800002b8 */
  Lumos: 696,
  /** AVA | Avalon | 0x800002b9 */
  Avalon: 697,
  /** VEIL | Veil | 0x800002ba */
  Veil: 698,
  /** GTB | GotaBit | 0x800002bb */
  Gotabit: 699,
  /** XDAI | xDai | 0x800002bc */
  Xdai: 700,
  /** COM | Commercio | 0x800002bd */
  Commercio: 701,
  /** CCC | Commercio Cash Credit | 0x800002be */
  CommercioCashCredit: 702,
  /** SNR | Sonr | 0x800002bf */
  Sonr: 703,
  /** RAQ | Ra Quantum | 0x800002c0 */
  RaQuantum: 704,
  /** PEG | Pegasus Token | 0x800002c1 */
  PegasusToken: 705,
  /** LKG | Lionking | 0x800002c2 */
  Lionking: 706,
  /** MCOIN | Moneta Coin | 0x800002c3 */
  MonetaCoin: 707,
  /** --- | reserved | 0x800002c4 */
  Coin708: 708,
  /** AVAIL | Avail | 0x800002c5 */
  Avail: 709,
  /** FURY | Highbury | 0x800002c6 */
  Highbury: 710,
  /** CHC | Chaincoin | 0x800002c7 */
  Chaincoin: 711,
  /** SERF | Serfnet | 0x800002c8 */
  Serfnet: 712,
  /** XTL | Katal Chain | 0x800002c9 */
  KatalChain: 713,
  /** BNB | Binance | 0x800002ca */
  Binance: 714,
  /** SIN | Sinovate | 0x800002cb */
  Sinovate: 715,
  /** DLN | Delion | 0x800002cc */
  Delion: 716,
  /** BONTE | Bontecoin | 0x800002cd */
  Bontecoin: 717,
  /** PEER | Peer | 0x800002ce */
  Peer: 718,
  /** ZET | Zetacoin | 0x800002cf */
  Zetacoin: 719,
  /** ABY | Artbyte | 0x800002d0 */
  Artbyte: 720,
  /** PGX | Mirai Chain | 0x800002d1 */
  MiraiChain: 721,
  /** IL8P | InfiniLooP | 0x800002d2 */
  Infiniloop: 722,
  /** VOI | Voi | 0x800002d3 */
  Voi: 723,
  /** XVC | Vanillacash | 0x800002d4 */
  Vanillacash: 724,
  /** MCX | MultiCash | 0x800002d5 */
  Multicash: 725,
  /** TARA | Taraxa | 0x800002d6 */
  Taraxa: 726,
  /** BLU | BluCrates | 0x800002d7 */
  Blucrates: 727,
  /** BFC | BFC | 0x800002d8 */
  Bfc: 728,
  /** DCC | DecentraCast | 0x800002d9 */
  Decentracast: 729,
  /** HEALIOS | Tenacity | 0x800002da */
  Tenacity: 730,
  /** BMK | Bitmark | 0x800002db */
  Bitmark: 731,
  /** FUGA | Fuga token | 0x800002dc */
  FugaToken: 732,
  /** TBC | TBChat | 0x800002dd */
  Tbchat: 733,
  /** DENTX | DENTNet | 0x800002de */
  Dentnet: 734,
  /** NBY | Neobytes | 0x800002df */
  Neobytes: 735,
  /** BABY | BABY | 0x800002e0 */
  Baby: 736,
  /** ATOP | Financial Blockchain | 0x800002e1 */
  FinancialBlockchain: 737,
  /** BTE | Bitweb | 0x800002e2 */
  Bitweb: 738,
  /** DPC | Dpowcoin (DualPowCoin) | 0x800002e3 */
  DpowcoinDualpowcoin: 739,
  /** MDC | MyDataCoin | 0x800002e4 */
  Mydatacoin: 740,
  /** RIV | Rigvid | 0x800002e5 */
  Rigvid: 741,
  /** LTO | LTO Network | 0x800002e6 */
  LtoNetwork742: 742,
  /** LKY | LuckyCoin | 0x800002e7 */
  Luckycoin: 743,
  /** DUSK | Dusk | 0x800002e8 */
  Dusk: 744,
  /** DIMI | DiminutiveCoin | 0x800002e9 */
  Diminutivecoin: 745,
  /** PLM | Palladium | 0x800002ea */
  Palladium: 746,
  /** CFG | Centrifuge | 0x800002eb */
  Centrifuge: 747,
  /** XPRT | Persistence | 0x800002ee */
  Persistence: 750,
  /** - | Age X25519 Encryption | 0x800002f1 */
  AgeX25519Encryption: 753,
  /** - | Age NIST Encryption | 0x800002f2 */
  AgeNistEncryption: 754,
  /** HONEY | HoneyWood | 0x800002f5 */
  Honeywood: 757,
  /** XDD | XDDCoin | 0x800002f6 */
  Xddcoin: 758,
  /** TBI | TBicloud | 0x800002f7 */
  Tbicloud: 759,
  /** FGC | Figcoin | 0x800002f8 */
  Figcoin: 760,
  /** BELLS | Bellscoin | 0x800002fa */
  Bellscoin: 762,
  /** TGN | Tagion | 0x800002fd */
  Tagion: 765,
  /** LLD | Liberland | 0x800002ff */
  Liberland: 767,
  /** BALLZ | Ballzcoin | 0x80000300 */
  Ballzcoin: 768,
  /** COSA | Cosanta | 0x80000302 */
  Cosanta: 770,
  /** BR | BR | 0x80000303 */
  Br: 771,
  /** CSB | CosmoBliss | 0x80000305 */
  Cosmobliss: 773,
  /** PLSR | Pulsar Coin | 0x80000307 */
  PulsarCoin: 775,
  /** KEY | Keymaker Coin | 0x80000308 */
  KeymakerCoin: 776,
  /** BTW | Bitcoin World | 0x80000309 */
  BitcoinWorld: 777,
  /** UCHAIN | UCHAIN | 0x8000030b */
  Uchain: 779,
  /** PLCUC | PLC Ultima Classic | 0x8000030c */
  PlcUltimaClassic: 780,
  /** PLCUX | PLC Ultima X | 0x8000030d */
  PlcUltimaX: 781,
  /** PLCU | PLC Ultima | 0x8000030e */
  PlcUltima: 782,
  /** SMARTBC | SMART Blockchain | 0x8000030f */
  SmartBlockchain: 783,
  /** SUI | Sui | 0x80000310 */
  Sui: 784,
  /** ULTIMA | ULTIMA | 0x80000311 */
  Ultima: 785,
  /** UIDD | UIDD | 0x80000312 */
  Uidd: 786,
  /** ACA | Acala | 0x80000313 */
  Acala: 787,
  /** BNC | Bifrost | 0x80000314 */
  Bifrost: 788,
  /** TAU | Lamden | 0x80000315 */
  Lamden: 789,
  /** LKY | Luckycoin | 0x80000316 */
  Luckycoin790: 790,
  /** SOMA | Soma | 0x80000317 */
  Soma: 791,
  /** INTR | Interlay | 0x8000031a */
  Interlay: 794,
  /** KINT | Kintsugi | 0x8000031b */
  Kintsugi: 795,
  /** MVRX | Muvor ERP | 0x8000031d */
  MuvorErp: 797,
  /** PDEX | Polkadex | 0x8000031f */
  Polkadex: 799,
  /** BEET | Beetle Coin | 0x80000320 */
  BeetleCoin: 800,
  /** DST | DSTRA | 0x80000321 */
  Dstra: 801,
  /** CY | Cyberyen | 0x80000322 */
  Cyberyen: 802,
  /** RYME | Ryme Network | 0x80000323 */
  RymeNetwork: 803,
  /** ZKS | zkSync | 0x80000324 */
  Zksync: 804,
  /** SCASH | Scash | 0x80000325 */
  Scash: 805,
  /** QVT | Qvolta | 0x80000328 */
  Qvolta: 808,
  /** SDN | Shiden Network | 0x80000329 */
  ShidenNetwork: 809,
  /** ASTR | Astar Network | 0x8000032a */
  AstarNetwork: 810,
  /** --- | reserved | 0x8000032b */
  Coin811: 811,
  /** MEER | Qitmeer | 0x8000032d */
  Qitmeer: 813,
  /** FACT | ImFACT | 0x8000032f */
  Imfact: 815,
  /** FSC | FSC | 0x80000330 */
  Fsc: 816,
  /** VET | VeChain Token | 0x80000332 */
  VechainToken: 818,
  /** REEF | Reef | 0x80000333 */
  Reef: 819,
  /** CLO | Callisto | 0x80000334 */
  Callisto: 820,
  /** BDB | BigchainDB | 0x80000336 */
  Bigchaindb: 822,
  /** TBL | TBLINK | 0x80000337 */
  Tblink: 823,
  /** RBNT | Redbelly Network | 0x80000338 */
  RedbellyNetwork: 824,
  /** YBC | YBChain | 0x8000033a */
  Ybchain: 826,
  /** ACE | Endurance | 0x8000033b */
  Endurance: 827,
  /** CCN | ComputeCoin | 0x8000033c */
  Computecoin: 828,
  /** BBA | BBACHAIN | 0x8000033d */
  Bbachain: 829,
  /** CRUZ | cruzbit | 0x8000033f */
  Cruzbit: 831,
  /** SAPP | Sapphire | 0x80000340 */
  Sapphire: 832,
  /** 777 | Jackpot | 0x80000341 */
  Jackpot: 833,
  /** KYAN | Kyanite | 0x80000342 */
  Kyanite: 834,
  /** AZR | Azzure | 0x80000343 */
  Azzure: 835,
  /** CFL | CryptoFlow | 0x80000344 */
  Cryptoflow: 836,
  /** DASHD | Dash Diamond | 0x80000345 */
  DashDiamond: 837,
  /** TRTT | Trittium | 0x80000346 */
  Trittium: 838,
  /** UCR | Ultra Clear | 0x80000347 */
  UltraClear: 839,
  /** PNY | Peony | 0x80000348 */
  Peony: 840,
  /** BECN | Beacon | 0x80000349 */
  Beacon: 841,
  /** MONK | Monk | 0x8000034a */
  Monk: 842,
  /** SAGA | CryptoSaga | 0x8000034b */
  Cryptosaga: 843,
  /** SUV | Suvereno | 0x8000034c */
  Suvereno: 844,
  /** ESK | EskaCoin | 0x8000034d */
  Eskacoin: 845,
  /** OWO | OneWorld Coin | 0x8000034e */
  OneworldCoin: 846,
  /** PEPS | PEPS Coin | 0x8000034f */
  PepsCoin: 847,
  /** BIR | Birake | 0x80000350 */
  Birake: 848,
  /** MOBIC | MobilityCoin | 0x80000351 */
  Mobilitycoin: 849,
  /** FLS | Flits | 0x80000352 */
  Flits: 850,
  /** FRECO | Freco | 0x80000353 */
  Freco: 851,
  /** DSM | Desmos | 0x80000354 */
  Desmos: 852,
  /** PRCY | PRCY Coin | 0x80000355 */
  PrcyCoin: 853,
  /** TB | TBCoin | 0x80000358 */
  Tbcoin: 856,
  /** HVH | HAVAH | 0x8000035a */
  Havah: 858,
  /** XBIT | XBIT Coin | 0x8000035c */
  XbitCoin: 860,
  /** CVM | Convex | 0x80000360 */
  Convex: 864,
  /** MOB | MobileCoin | 0x80000362 */
  Mobilecoin: 866,
  /** IF | Infinitefuture | 0x80000364 */
  Infinitefuture: 868,
  /** TXFLOW | TxFlow | 0x80000365 */
  Txflow: 869,
  /** QUORUM | Quorum | 0x80000369 */
  Quorum: 873,
  /** NAM | Namada | 0x8000036d */
  Namada: 877,
  /** SCR | Scorum Network | 0x8000036e */
  ScorumNetwork: 878,
  /** LUM | Lum Network | 0x80000370 */
  LumNetwork: 880,
  /** AEGS | Aegisum | 0x80000371 */
  Aegisum: 881,
  /** ZBC | ZooBC | 0x80000373 */
  Zoobc: 883,
  /** XCN | XCoin | 0x80000375 */
  Xcoin: 885,
  /** ADF | AD Token | 0x80000376 */
  AdToken: 886,
  /** NEO | NEO | 0x80000378 */
  Neo: 888,
  /** TOMO | TOMO | 0x80000379 */
  Tomo: 889,
  /** XSEL | Seln | 0x8000037a */
  Seln: 890,
  /** LKSC | LKSCoin | 0x80000380 */
  Lkscoin: 896,
  /** AS | Assetchain | 0x80000382 */
  Assetchain: 898,
  /** XEC | eCash | 0x80000383 */
  Ecash: 899,
  /** LMO | Lumeneo | 0x80000384 */
  Lumeneo: 900,
  /** NXT | NxtMeta | 0x80000385 */
  Nxtmeta: 901,
  /** EGN | EGAHN Intelligence Network | 0x80000387 */
  EgahnIntelligenceNetwork: 903,
  /** HNT | Helium | 0x80000388 */
  Helium904: 904,
  /** XPX | Sirius | 0x8000038a */
  Sirius: 906,
  /** FIS | StaFi | 0x8000038b */
  Stafi: 907,
  /** SGE | Saage | 0x8000038d */
  Saage: 909,
  /** GERT | Gert | 0x8000038f */
  Gert: 911,
  /** VARA | Vara Network | 0x80000391 */
  VaraNetwork: 913,
  /** META | Metadium | 0x80000394 */
  Metadium: 916,
  /** FRA | Findora | 0x80000395 */
  Findora: 917,
  /** CCD | Concordium | 0x80000397 */
  Concordium: 919,
  /** AVN | Avian Network | 0x80000399 */
  AvianNetwork: 921,
  /** DIP | Dipper Network | 0x8000039d */
  DipperNetwork: 925,
  /** GHM | HermitMatrixNetwork | 0x800003a0 */
  Hermitmatrixnetwork: 928,
  /** RUNE | THORChain (RUNE) | 0x800003a3 */
  ThorchainRune: 931,
  /** MGO | Mango Network | 0x800003aa */
  MangoNetwork: 938,
  /** AB | Argot Protocol | 0x800003ab */
  ArgotProtocol: 939,
  /** --- | reserved | 0x800003ad */
  Coin941: 941,
  /** KCN | Kylacoin | 0x800003ae */
  Kylacoin: 942,
  /** LCN | Lyncoin | 0x800003af */
  Lyncoin: 943,
  /** UNLOCK | Jasiri protocol | 0x800003b1 */
  JasiriProtocol: 945,
  /** CNDT | Conduct Protocol | 0x800003b6 */
  ConductProtocol: 950,
  /** LTP | LifetionCoin | 0x800003bb */
  Lifetioncoin: 955,
  /** - | KickSoccer | 0x800003be */
  Kicksoccer: 958,
  /** VKAX | Vkax | 0x800003c0 */
  Vkax: 960,
  /** SYL | OpenSY | 0x800003c3 */
  Opensy: 963,
  /** ATLA | Atleta Network | 0x800003c5 */
  AtletaNetwork: 965,
  /** MATIC | Matic | 0x800003c6 */
  Matic: 966,
  /** UNW | UNW | 0x800003c8 */
  Unw: 968,
  /** QI | Quai Network | 0x800003c9 */
  QuaiNetwork: 969,
  /** TWINS | TWINS | 0x800003ca */
  Twins: 970,
  /** - | TrustNet | 0x800003cf */
  Trustnet: 975,
  /** TLOS | Telos | 0x800003d1 */
  Telos: 977,
  /** TAFECO | Taf ECO Chain | 0x800003d5 */
  TafEcoChain: 981,
  /** AU | Autonomy | 0x800003d9 */
  Autonomy: 985,
  /** VCG | VipCoin | 0x800003db */
  Vipcoin: 987,
  /** XAZAB | Xazab core | 0x800003dc */
  XazabCore: 988,
  /** AIOZ | AIOZ | 0x800003dd */
  Aioz: 989,
  /** CORE | Coreum | 0x800003de */
  Coreum: 990,
  /** PEC | Phoenix | 0x800003df */
  Phoenix: 991,
  /** UNT | Unit | 0x800003e0 */
  Unit: 992,
  /** XRB | X Currency | 0x800003e1 */
  XCurrency: 993,
  /** QUAI | Quai Network | 0x800003e2 */
  QuaiNetwork994: 994,
  /** CAPS | Ternoa | 0x800003e3 */
  Ternoa: 995,
  /** OKT | OKChain Token | 0x800003e4 */
  OkchainToken: 996,
  /** SUM | Solidum | 0x800003e5 */
  Solidum: 997,
  /** LBTC | Lightning Bitcoin | 0x800003e6 */
  LightningBitcoin: 998,
  /** BCD | Bitcoin Diamond | 0x800003e7 */
  BitcoinDiamond: 999,
  /** BTN | Bitcoin New | 0x800003e8 */
  BitcoinNew: 1000,
  /** TT | ThunderCore | 0x800003e9 */
  Thundercore: 1001,
  /** BKT | BanKitt | 0x800003ea */
  Bankitt: 1002,
  /** NODL | Nodle | 0x800003eb */
  Nodle: 1003,
  /** PCOIN | PCOIN | 0x800003ec */
  Pcoin: 1004,
  /** TAO | Bittensor | 0x800003ed */
  Bittensor: 1005,
  /** HSK | HashKey Chain | 0x800003ee */
  HashkeyChain: 1006,
  /** FTM | Fantom | 0x800003ef */
  Fantom: 1007,
  /** RPG | RPG | 0x800003f0 */
  Rpg: 1008,
  /** LAKE | iconLake | 0x800003f1 */
  Iconlake: 1009,
  /** HT | Huobi ECO Chain | 0x800003f2 */
  HuobiEcoChain: 1010,
  /** ELV | Eluvio | 0x800003f3 */
  Eluvio: 1011,
  /** JOC | Japan Open Chain | 0x800003f4 */
  JapanOpenChain: 1012,
  /** BIC | Beincrypto | 0x800003f5 */
  Beincrypto: 1013,
  /** JOY | Joystream | 0x800003f6 */
  Joystream: 1014,
  /** ZCX | ZEN Exchange Token | 0x800003f7 */
  ZenExchangeToken: 1015,
  /** --- | reserved | 0x800003f8 */
  Coin1016: 1016,
  /** ZTC | Zenchain | 0x800003f9 */
  Zenchain: 1017,
  /** ZANO | Zano | 0x800003fa */
  Zano: 1018,
  /** ZENO | Zenotta | 0x800003fb */
  Zenotta: 1019,
  /** EVC | Evrice | 0x800003fc */
  Evrice: 1020,
  /** PKOIN | Pocketcoin | 0x800003fd */
  Pocketcoin: 1021,
  /** XRD | Radix DLT | 0x800003fe */
  RadixDlt: 1022,
  /** ONE | HARMONY-ONE (Legacy) | 0x800003ff */
  HarmonyOneLegacy: 1023,
  /** ONT | Ontology | 0x80000400 */
  Ontology: 1024,
  /** CZZ | Classzz | 0x80000401 */
  Classzz: 1025,
  /** KEX | Kira Exchange Token | 0x80000402 */
  KiraExchangeToken: 1026,
  /** MCM | Mochimo | 0x80000403 */
  Mochimo: 1027,
  /** PLS | Pulse Coin | 0x80000404 */
  PulseCoin: 1028,
  /** BTCR | BTCR | 0x80000408 */
  Btcr: 1032,
  /** MFID | Moonfish ID | 0x80000412 */
  MoonfishId: 1042,
  /** CROSS | Cross Chain | 0x8000044c */
  CrossChain: 1100,
  /** ZRA | ZERA | 0x80000456 */
  Zera: 1110,
  /** BBC | Big Bitcoin | 0x80000457 */
  BigBitcoin: 1111,
  /** CORE | Core | 0x8000045c */
  Core: 1116,
  /** RISE | RISE | 0x80000460 */
  Rise: 1120,
  /** CMT | CyberMiles Token | 0x80000462 */
  CybermilesToken: 1122,
  /** ETSC | Ethereum Social | 0x80000468 */
  EthereumSocial: 1128,
  /** DFI | DeFiChain | 0x80000469 */
  Defichain: 1129,
  /** DFI | DeFiChain EVM Network | 0x8000046a */
  DefichainEvmNetwork: 1130,
  /** MESH | StateMesh | 0x8000046e */
  Statemesh: 1134,
  /** $DAG | Constellation Labs | 0x80000471 */
  ConstellationLabs: 1137,
  /** CDY | Bitcoin Candy | 0x80000479 */
  BitcoinCandy: 1145,
  /** ENJ | Enjin Coin | 0x80000483 */
  EnjinCoin: 1155,
  /** HOO | Hoo Smart Chain | 0x80000492 */
  HooSmartChain: 1170,
  /** GNK | Gonka | 0x800004b0 */
  Gonka: 1200,
  /** ALPH | Alephium | 0x800004d2 */
  Alephium: 1234,
  /** - | Masca | 0x800004d4 */
  Masca: 1236,
  /** - | Nostr | 0x800004d5 */
  Nostr: 1237,
  /** - | Kudos Setler | 0x80000500 */
  KudosSetler: 1280,
  /** GLMR | Moonbeam | 0x80000504 */
  Moonbeam: 1284,
  /** MOVR | Moonriver | 0x80000505 */
  Moonriver: 1285,
  /** DSG | Dessage Social Protocol | 0x80000506 */
  DessageSocialProtocol: 1286,
  /** WPC | Wpc | 0x80000512 */
  Wpc: 1298,
  /** WEI | WEI | 0x8000051c */
  Wei: 1308,
  /** BITS | Entropy | 0x80000520 */
  Entropy: 1312,
  /** DFC | Defcoin | 0x80000539 */
  Defcoin: 1337,
  /** IRON | Iron Fish | 0x8000053a */
  IronFish: 1338,
  /** WNSD | Winsdet | 0x8000053b */
  Winsdet: 1339,
  /** ISLM | IslamicCoin | 0x80000544 */
  Islamiccoin: 1348,
  /** HYC | Hycon | 0x80000575 */
  Hycon: 1397,
  /** TENTSLP | TENT Simple Ledger Protocol | 0x80000582 */
  TentSimpleLedgerProtocol: 1410,
  /** DEV | DogecoinEV | 0x8000058c */
  Dogecoinev: 1420,
  /** DNR | Dinero | 0x800005a7 */
  Dinero1447: 1447,
  /** XSC | XT Smart Chain | 0x800005e6 */
  XtSmartChain: 1510,
  /** AAC | Double-A Chain | 0x800005e8 */
  DoubleAChain: 1512,
  /** - | Taler | 0x800005f4 */
  Taler: 1524,
  /** BEAM | Beam | 0x800005fd */
  Beam: 1533,
  /** GAS | BubiChain | 0x80000600 */
  Bubichain: 1536,
  /** ATHENA | Athena | 0x80000604 */
  Athena: 1540,
  /** SDK | Sovereign SDK | 0x8000060f */
  SovereignSdk: 1551,
  /** APC | Apc Chain | 0x80000613 */
  ApcChain: 1555,
  /** ELF | AELF | 0x80000650 */
  Aelf: 1616,
  /** AUDL | AUDL | 0x80000652 */
  Audl: 1618,
  /** ATH | Atheios | 0x80000654 */
  Atheios: 1620,
  /** LUME | Lume Web | 0x8000065b */
  LumeWeb: 1627,
  /** NEW | Newton | 0x8000066a */
  Newton: 1642,
  /** BTA | Btachain | 0x80000679 */
  Btachain: 1657,
  /** NEOX | Neoxa | 0x80000684 */
  Neoxa: 1668,
  /** MEWC | Meowcoin | 0x80000685 */
  Meowcoin: 1669,
  /** BCX | BitcoinX | 0x80000698 */
  Bitcoinx: 1688,
  /** TRMP | TrumPOW | 0x800006ab */
  Trumpow: 1707,
  /** XTZ | Tezos | 0x800006c1 */
  Tezos: 1729,
  /** LBTC | Liquid BTC | 0x800006f0 */
  LiquidBtc: 1776,
  /** BBP | Biblepay | 0x800006f1 */
  Biblepay: 1777,
  /** JPYS | JPY Stablecoin | 0x800006f8 */
  JpyStablecoin: 1784,
  /** USVAC | USVACoin | 0x800006fc */
  Usvacoin: 1788,
  /** VEGA | Vega Protocol | 0x800006fd */
  VegaProtocol: 1789,
  /** ADA | Cardano | 0x80000717 */
  Cardano: 1815,
  /** CUBE | Cube Chain Native Token | 0x8000071a */
  CubeChainNativeToken: 1818,
  /** ZTX | Zetrix | 0x80000760 */
  Zetrix: 1888,
  /** XEC | eCash token | 0x8000076b */
  EcashToken: 1899,
  /** XNA | Neurai | 0x8000076c */
  Neurai: 1900,
  /** CLC | Classica | 0x8000076d */
  Classica: 1901,
  /** BITCI | Bitcicoin | 0x80000773 */
  Bitcicoin: 1907,
  /** BKC | Briskcoin | 0x8000077e */
  Briskcoin: 1918,
  /** VIPS | VIPSTARCOIN | 0x8000077f */
  Vipstarcoin: 1919,
  /** CITY | City Coin | 0x80000786 */
  CityCoin: 1926,
  /** HRC | Hypercoin | 0x8000078f */
  Hypercoin: 1935,
  /** ESA | Esa | 0x8000079f */
  Esa: 1951,
  /** ESC | EsaCoin | 0x800007a0 */
  Esacoin: 1952,
  /** XX | xx coin | 0x800007a3 */
  XxCoin: 1955,
  /** MVRK | Mavryk Network | 0x800007b1 */
  MavrykNetwork: 1969,
  /** XMX | Xuma | 0x800007b9 */
  Xuma: 1977,
  /** TRTL | TurtleCoin | 0x800007c0 */
  Turtlecoin: 1984,
  /** SLRT | Solarti Chain | 0x800007c1 */
  SolartiChain: 1985,
  /** QTH | Qing Tong Horizon | 0x800007c2 */
  QingTongHorizon: 1986,
  /** EGEM | EtherGem | 0x800007c3 */
  Ethergem: 1987,
  /** MIRA | Mira Chain | 0x800007c4 */
  MiraChain: 1988,
  /** HODL | HOdlcoin | 0x800007c5 */
  Hodlcoin: 1989,
  /** PHL | Placeholders | 0x800007c6 */
  Placeholders: 1990,
  /** SC | Sia | 0x800007c7 */
  Sia: 1991,
  /** MYDOGE | Mydogecoin | 0x800007cb */
  Mydogecoin: 1995,
  /** MYT | Mineyourtime | 0x800007cc */
  Mineyourtime: 1996,
  /** POLIS | Polis | 0x800007cd */
  Polis: 1997,
  /** XMCC | Monoeci | 0x800007ce */
  Monoeci: 1998,
  /** COLX | ColossusXT | 0x800007cf */
  Colossusxt: 1999,
  /** GIN | GinCoin | 0x800007d0 */
  Gincoin: 2000,
  /** MNP | MNPCoin | 0x800007d1 */
  Mnpcoin: 2001,
  /** MLN | Miraland | 0x800007d2 */
  Miraland: 2002,
  /** ISNA | iSarrana | 0x800007d3 */
  Isarrana: 2003,
  /** XBT | Bitcoin Classic | 0x800007da */
  BitcoinClassic: 2010,
  /** JKC | Junkcoin | 0x800007dd */
  Junkcoin: 2013,
  /** TEER | Integritee | 0x800007df */
  Integritee: 2015,
  /** KIN | Kin | 0x800007e1 */
  Kin: 2017,
  /** EOSC | EOSClassic | 0x800007e2 */
  Eosclassic: 2018,
  /** GBT | GoldBean Token | 0x800007e3 */
  GoldbeanToken: 2019,
  /** PKC | PKC | 0x800007e4 */
  Pkc: 2020,
  /** SKT | Sukhavati | 0x800007e5 */
  Sukhavati: 2021,
  /** XHT | Xinghuo Token | 0x800007e6 */
  XinghuoToken: 2022,
  /** COC | Chat On Chain | 0x800007e7 */
  ChatOnChain: 2023,
  /** USBC | Universal Ledger USBC | 0x800007e8 */
  UniversalLedgerUsbc: 2024,
  /** ROCK | Zenrock Labs | 0x800007e9 */
  ZenrockLabs: 2025,
  /** ASTRON | ASTRON Token | 0x800007ea */
  AstronToken: 2026,
  /** ANY | Any | 0x800007fe */
  Any: 2046,
  /** MCASH | MCashChain | 0x80000800 */
  Mcashchain: 2048,
  /** TRUE | TrueChain | 0x80000801 */
  Truechain: 2049,
  /** MOVO | Movo Smart Chain | 0x80000802 */
  MovoSmartChain: 2050,
  /** KILT | KILT Spiritnet | 0x80000826 */
  KiltSpiritnet: 2086,
  /** FRQCY | Frequency | 0x8000082b */
  Frequency: 2091,
  /** SAMA | Exosama Network | 0x8000083d */
  ExosamaNetwork: 2109,
  /** IoTE | IoTE | 0x80000840 */
  Iote: 2112,
  /** CBTC | Coordinate BTC (Anduro) | 0x80000849 */
  CoordinateBtcAnduro: 2121,
  /** QBTC | Quasar BTC (Anduro) | 0x8000084a */
  QuasarBtcAnduro: 2122,
  /** BAY | BitBay | 0x8000084d */
  Bitbay: 2125,
  /** XRG | Ergon | 0x80000859 */
  Ergon: 2137,
  /** SAMA | Moonsama Network | 0x80000897 */
  MoonsamaNetwork: 2199,
  /** ASK | ASK | 0x800008ad */
  Ask: 2221,
  /** CWEB | Coinweb | 0x800008ae */
  Coinweb: 2222,
  /** - | Qiyi Chain | 0x800008ed */
  QiyiChain: 2285,
  /** QTUM | QTUM | 0x800008fd */
  Qtum: 2301,
  /** ETP | Metaverse | 0x800008fe */
  Metaverse: 2302,
  /** GXC | GXChain | 0x800008ff */
  Gxchain: 2303,
  /** CRP | CranePay | 0x80000900 */
  Cranepay: 2304,
  /** ELA | Elastos | 0x80000901 */
  Elastos: 2305,
  /** SNOW | Snowblossom | 0x80000922 */
  Snowblossom: 2338,
  /** XIN | Mixin | 0x8000093d */
  Mixin: 2365,
  /** HYPE | Hyperliquid | 0x80000999 */
  Hyperliquid: 2457,
  /** NEXI | Nexi | 0x800009c4 */
  Nexi: 2500,
  /** AOA | Aurora | 0x80000a0a */
  Aurora: 2570,
  /** AIPG | AIPowerGrid | 0x80000a7e */
  Aipowergrid: 2686,
  /** NAS | Nebulas | 0x80000a9e */
  Nebulas: 2718,
  /** LAN | Lanify | 0x80000af9 */
  Lanify: 2809,
  /** REOSC | REOSC Ecosystem | 0x80000b4e */
  ReoscEcosystem: 2894,
  /** BND | Blocknode | 0x80000b7d */
  Blocknode: 2941,
  /** SM | Stealth Message | 0x80000bb8 */
  StealthMessage: 3000,
  /** LUX | LUX | 0x80000bbb */
  Lux: 3003,
  /** HBAR | Hedera HBAR | 0x80000bd6 */
  HederaHbar: 3030,
  /** HIVE | Hive Blockchain | 0x80000bee */
  HiveBlockchain: 3054,
  /** COS | Contentos | 0x80000c05 */
  Contentos: 3077,
  /** DIP | Dipnet Blockchain | 0x80000c3b */
  DipnetBlockchain: 3131,
  /** B1T | Bit | 0x80000c45 */
  Bit: 3141,
  /** CCC | CodeChain | 0x80000ccc */
  Codechain: 3276,
  /** SXP | Solar | 0x80000d05 */
  Solar: 3333,
  /** PEAQ | peaq | 0x80000d0a */
  Peaq: 3338,
  /** PLMC | Polimec | 0x80000d10 */
  Polimec: 3344,
  /** ROI | ROIcoin | 0x80000d31 */
  Roicoin: 3377,
  /** DYN | Dynamic | 0x80000d35 */
  Dynamic: 3381,
  /** SEQ | Sequence | 0x80000d37 */
  Sequence: 3383,
  /** PEPE | Pepecoin Core | 0x80000d6a */
  PepecoinCore: 3434,
  /** BLAZE | Blaze | 0x80000dab */
  Blaze: 3499,
  /** JFIN | JFIN Coin | 0x80000dad */
  JfinCoin: 3501,
  /** DEO | Destocoin | 0x80000de0 */
  Destocoin: 3552,
  /** DST | DeStream | 0x80000dec */
  Destream: 3564,
  /** CY | Cybits | 0x80000e11 */
  Cybits: 3601,
  /** EPPIE | Eppie | 0x80000e2e */
  Eppie: 3630,
  /** MPC | Partisia Blockchain | 0x80000ead */
  PartisiaBlockchain: 3757,
  /** RED | ReDeFi RED | 0x80000f00 */
  RedefiRed: 3840,
  /** FC8 | FCH Network | 0x80000fc8 */
  FchNetwork: 4040,
  /** YEE | YeeCo | 0x80001000 */
  Yeeco: 4096,
  /** IOTA | IOTA | 0x8000107a */
  Iota: 4218,
  /** SMR | Shimmer | 0x8000107b */
  Shimmer: 4219,
  /** AXE | Axe | 0x80001092 */
  Axe: 4242,
  /** LOCA | Loca | 0x800010CA */
  Loca: 4298,
  /** XYM | Symbol | 0x800010f7 */
  Symbol: 4343,
  /** C4E | Chain4Energy | 0x8000115c */
  Chain4energy: 4444,
  /** SHIC | ShibaCoin | 0x8000117a */
  Shibacoin: 4474,
  /** MST | MST | 0x80001226 */
  Mst: 4646,
  /** XVM | Venidium | 0x80001337 */
  Venidium: 4919,
  /** VARA | Vara | 0x80001370 */
  Vara: 4976,
  /** BXN | BlackFort Exchange Network | 0x80001387 */
  BlackfortExchangeNetwork: 4999,
  /** V12 | Vet The Vote | 0x80001388 */
  VetTheVote: 5000,
  /** SBC | Senior Blockchain | 0x8000138e */
  SeniorBlockchain: 5006,
  /** FIC | FIC | 0x80001480 */
  Fic: 5248,
  /** HNS | Handshake | 0x800014e9 */
  Handshake: 5353,
  /** ISK | ISKRA | 0x8000151c */
  Iskra: 5404,
  /** ALTME | ALTME | 0x8000155b */
  Altme: 5467,
  /** FUND | Unification | 0x800015b3 */
  Unification: 5555,
  /** STX | Stacks | 0x8000167d */
  Stacks: 5757,
  /** VOW | VowChain VOW | 0x80001707 */
  VowchainVow: 5895,
  /** SLU | SILUBIUM | 0x80001720 */
  Silubium: 5920,
  /** DUSK | Dusk Network | 0x8000176b */
  DuskNetwork: 5995,
  /** GO | GoChain GO | 0x800017ac */
  GochainGo: 6060,
  /** DTS | Datos | 0x80001800 */
  Datos: 6144,
  /** MOI | My Own Internet | 0x8000181e */
  MyOwnInternet: 6174,
  /** STEAMX | Rails Network Mainnet | 0x80001886 */
  RailsNetworkMainnet: 6278,
  /** VRL | Virel Protocol | 0x800018a6 */
  VirelProtocol: 6310,
  /** NEUE | Dap | 0x800018ef */
  Dap: 6383,
  /** UM | Penumbra | 0x80001984 */
  Penumbra: 6532,
  /** RSC | Royal Sports City | 0x800019c7 */
  RoyalSportsCity: 6599,
  /** BPA | Bitcoin Pizza | 0x80001a0a */
  BitcoinPizza: 6666,
  /** SAFE | SAFE | 0x80001a20 */
  Safe: 6688,
  /** CC | Canton Coin | 0x80001a6f */
  CantonCoin: 6767,
  /** COTI | COTI | 0x80001a7b */
  Coti: 6779,
  /** ROGER | TheHolyrogerCoin | 0x80001b39 */
  Theholyrogercoin: 6969,
  /** ZETA | ZetaChain | 0x80001b58 */
  Zetachain: 7000,
  /** ELLA | Ella the heart | 0x80001b73 */
  EllaTheHeart: 7027,
  /** AA | Arthera | 0x80001b74 */
  Arthera: 7028,
  /** DOI | Doichain | 0x80001b9e */
  Doichain: 7070,
  /** TOPL | Topl | 0x80001bb3 */
  Topl: 7091,
  /** ABTC | Alys BTC (Anduro) | 0x80001c68 */
  AlysBtcAnduro: 7272,
  /** KLY | KLYNTAR | 0x80001ca3 */
  Klyntar: 7331,
  /** SHFT | Shyft | 0x80001cad */
  Shyft: 7341,
  /** MEV | MEVerse | 0x80001d5e */
  Meverse: 7518,
  /** ADIL | ADIL Chain | 0x80001d98 */
  AdilChain: 7576,
  /** BTV | Bitvote | 0x80001e61 */
  Bitvote: 7777,
  /** CPV | Compverse | 0x80001e63 */
  Compverse: 7779,
  /** SKY | Skycoin | 0x80001f40 */
  Skycoin: 8000,
  /** BERA | Berachain | 0x80001f48 */
  Berachain: 8008,
  /** ISC | iSunCoin | 0x80001f51 */
  Isuncoin: 8017,
  /** - | DSRV | 0x80001f90 */
  Dsrv: 8080,
  /** BOC | BeOne Chain | 0x80001ff5 */
  BeoneChain: 8181,
  /** PAC | pacprotocol | 0x80002000 */
  Pacprotocol: 8192,
  /** KAIA | KAIA | 0x80002019 */
  Kaia: 8217,
  /** HANEUL | Haneul | 0x8000205a */
  Haneul: 8282,
  /** BTQ | BitcoinQuark | 0x80002093 */
  Bitcoinquark: 8339,
  /** XCH | Chia | 0x800020fc */
  Chia: 8444,
  /** - | Base | 0x80002105 */
  Base: 8453,
  /** --- | reserved | 0x80002148 */
  Coin8520: 8520,
  /** PLMNT | Planetmint | 0x800021e8 */
  Planetmint: 8680,
  /** BLN | Bullions | 0x8000221c */
  Bullions: 8732,
  /** ALPH | Alph Network | 0x80002222 */
  AlphNetwork: 8738,
  /** GGX | Golden Gate | 0x800022a2 */
  GoldenGate: 8866,
  /** GGXT | Golden Gate Sydney | 0x800022b6 */
  GoldenGateSydney: 8886,
  /** KTA | Keeta | 0x800022b7 */
  Keeta: 8887,
  /** SBTC | Super Bitcoin | 0x800022b8 */
  SuperBitcoin: 8888,
  /** NULS | NULS | 0x80002304 */
  Nuls: 8964,
  /** BBC | Babacoin | 0x80002325 */
  Babacoin: 8997,
  /** JGC | JagoanCoin | 0x80002326 */
  Jagoancoin: 8998,
  /** BTP | Bitcoin Pay | 0x80002327 */
  BitcoinPay: 8999,
  /** AVAX | Avalanche | 0x80002328 */
  Avalanche: 9000,
  /** ARB1 | Arbitrum | 0x80002329 */
  Arbitrum: 9001,
  /** BOBA | Boba | 0x8000232a */
  Boba: 9002,
  /** LOOP | Loopring | 0x8000232b */
  Loopring: 9003,
  /** STRK | StarkNet | 0x8000232c */
  Starknet: 9004,
  /** AVAXC | Avalanche C-Chain | 0x8000232d */
  AvalancheCChain: 9005,
  /** BSC | Binance Smart Chain | 0x8000232e */
  BinanceSmartChain: 9006,
  /** SATOX | Satoxcoin | 0x8000232f */
  Satoxcoin: 9007,
  /** WEIL | Weilliptic | 0x80002481 */
  Weilliptic: 9345,
  /** RIN | Rincoin | 0x80002553 */
  Rincoin: 9555,
  /** NRG | Energi | 0x80002645 */
  Energi: 9797,
  /** BTF | Bitcoin Faith | 0x800026a0 */
  BitcoinFaith: 9888,
  /** OSMI | Osmium | 0x800026f1 */
  Osmium: 9969,
  /** GOD | Bitcoin God | 0x8000270f */
  BitcoinGod: 9999,
  /** FO | FIBOS | 0x80002710 */
  Fibos: 10000,
  /** SPACE | Space | 0x80002711 */
  Space: 10001,
  /** S | SONIC | 0x80002717 */
  Sonic: 10007,
  /** DHP | dHealth | 0x8000277f */
  Dhealth: 10111,
  /** RTM | Raptoreum | 0x800027f2 */
  Raptoreum: 10226,
  /** AA | Arthera | 0x80002802 */
  Arthera10242: 10242,
  /** XRC | XRhodium | 0x80002833 */
  Xrhodium: 10291,
  /** NUM | Numbers Protocol | 0x8000290b */
  NumbersProtocol: 10507,
  /** XPI | Lotus | 0x8000296d */
  Lotus: 10605,
  /** ESS | Essentia One | 0x80002b67 */
  EssentiaOne: 11111,
  /** VARCH | InvArch | 0x80002dde */
  Invarch: 11742,
  /** TNKR | Tinkernet | 0x80002ddf */
  Tinkernet: 11743,
  /** AURE | Aureus | 0x80002edb */
  Aureus: 11995,
  /** IPOS | IPOS | 0x80003039 */
  Ipos: 12345,
  /** MINA | Mina | 0x8000312a */
  Mina: 12586,
  /** ANLOG | Analog Timechain | 0x80003232 */
  AnalogTimechain: 12850,
  /** BTY | BitYuan | 0x80003333 */
  Bityuan: 13107,
  /** YCC | Yuan Chain Coin | 0x80003334 */
  YuanChainCoin: 13108,
  /** PHX | Phoenix | 0x80003445 */
  Phoenix13381: 13381,
  /** WAX | Worldwide Asset Exchange | 0x800036b1 */
  WorldwideAssetExchange: 14001,
  /** SDGO | SanDeGo | 0x80003de5 */
  Sandego: 15845,
  /** XTX | Totem Live Network | 0x80003f35 */
  TotemLiveNetwork: 16181,
  /** ARDR | Ardor | 0x80004172 */
  Ardor: 16754,
  /** MTR | Meter | 0x80004650 */
  Meter: 18000,
  /** SAFE | Safecoin | 0x80004add */
  Safecoin: 19165,
  /** FLUX | Flux | 0x80004adf */
  Flux: 19167,
  /** RITO | Ritocoin | 0x80004ae1 */
  Ritocoin: 19169,
  /** ML | Mintlayer | 0x80004d4c */
  Mintlayer: 19788,
  /** XND | ndau | 0x80004e44 */
  Ndau: 20036,
  /** WJK | WojakCoin | 0x80005118 */
  Wojakcoin: 20760,
  /** C4EI | c4ei | 0x8000520c */
  C4ei: 21004,
  /** XAH | Xahau | 0x80005359 */
  Xahau: 21337,
  /** PAC | Pactus | 0x80005580 */
  Pactus: 21888,
  /** PWR | PWRcoin | 0x800057e8 */
  Pwrcoin: 22504,
  /** EPIC | Epic Cash | 0x800059d8 */
  EpicCash: 23000,
  /** BELL | Bellcoin | 0x800062a4 */
  Bellcoin: 25252,
  /** CHX | Own | 0x80006476 */
  Own: 25718,
  /** G1 | Ğ1 | 0x80006731 */
  G1: 26417,
  /** NEXA | Nexa | 0x80007227 */
  Nexa: 29223,
  /** --- | reserved | 0x80007531 */
  Coin30001: 30001,
  /** ESN | EtherSocial Network | 0x8000797e */
  EthersocialNetwork: 31102,
  /** - | ThePower | 0x80007a69 */
  Thepower: 31337,
  /** TEO | Trust Eth reOrigin | 0x80008288 */
  TrustEthReorigin: 33416,
  /** BTCS | Bitcoin Stake | 0x80008456 */
  BitcoinStake: 33878,
  /** BTT | ByteTrade | 0x80008888 */
  Bytetrade: 34952,
  /** AMA | AMA | 0x80009069 */
  Ama: 36969,
  /** FXTC | FixedTradeCoin | 0x80009468 */
  Fixedtradecoin: 37992,
  /** AMA | Amabig | 0x80009999 */
  Amabig: 39321,
  /** FACT | FACT0RN | 0x8000a455 */
  Fact0rn: 42069,
  /** AXIV | AXIV | 0x8000a814 */
  Axiv: 43028,
  /** BAX | BAX | 0x8000babb */
  Bax: 47803,
  /** EVE | evan | 0x8000c06e */
  Evan: 49262,
  /** STASH | STASH | 0x8000c0c0 */
  Stash: 49344,
  /** CELO | Celo | 0x8000ce10 */
  Celo: 52752,
  /** OVER | OverProtocol | 0x8000d3a0 */
  Overprotocol: 54176,
  /** TH | TianHe | 0x8000f0b0 */
  Tianhe: 61616,
  /** MORM | Morpheum | 0x8000f200 */
  Morpheum: 61888,
  /** KETH | Krypton World | 0x80010000 */
  KryptonWorld: 65536,
  /** GRLC | Garlicoin | 0x80010f2c */
  Garlicoin: 69420,
  /** GWL | Gewel | 0x80011177 */
  Gewel: 70007,
  /** ZYN | Wethio | 0x80012fd1 */
  Wethio: 77777,
  /** QUBIC | Qubic | 0x8001455d */
  Qubic: 83293,
  /** RYO | c0ban | 0x80015b38 */
  C0ban: 88888,
  /** WICC | Waykichain | 0x8001869f */
  Waykichain: 99999,
  /** HOME | HomeCoin | 0x80018894 */
  Homecoin: 100500,
  /** STC | Starcoin | 0x80018a92 */
  Starcoin: 101010,
  /** - | Seed Hypermedia | 0x800196ad */
  SeedHypermedia: 104109,
  /** STRAX | Strax | 0x80019a91 */
  Strax: 105105,
  /** KAS | Kaspa | 0x8001b207 */
  Kaspa: 111111,
  /** KLS | Karlsen | 0x8001d9f9 */
  Karlsen: 121337,
  /** SPR | Spectre | 0x8001e240 */
  Spectre: 123456,
  /** WBT | WhiteBIT Coin | 0x8001ff06 */
  WhitebitCoin: 130822,
  /** APTA | Bloqs4Good | 0x8002780b */
  Bloqs4good: 161803,
  /** QUAN | Quantus Network | 0x8002e305 */
  QuantusNetwork: 189189,
  /** AKA | Akroma | 0x80030fb1 */
  Akroma: 200625,
  /** BTR | Bitlayer | 0x800310c5 */
  Bitlayer: 200901,
  /** CONET | CONET Holesky Network | 0x80036cb1 */
  ConetHoleskyNetwork: 224433,
  /** ATS | ARTIS sigma1 | 0x8003c301 */
  ArtisSigma1: 246529,
  /** AUTOX | Autox Coin | 0x8003d48e */
  AutoxCoin: 251022,
  /** ZAMA | Zama | 0x8003fc0b */
  Zama: 261131,
  /** PI | Pi Network | 0x8004cb2f */
  PiNetwork: 314159,
  /** VALUE | Value Chain | 0x80051614 */
  ValueChain: 333332,
  /** 3333 | Pi Value Consensus | 0x80051615 */
  PiValueConsensus: 333333,
  /** X42 | x42 | 0x80067932 */
  X42: 424242,
  /** @G | Graphite | 0x8006b6d1 */
  Graphite: 440017,
  /** SCR | Scroll | 0x80082750 */
  Scroll: 534352,
  /** VITE | Vite | 0x800a2c2a */
  Vite: 666666,
  /** ICE | Ice Network | 0x800b3206 */
  IceNetwork: 696365,
  /** TXC | TEXITcoin | 0x800aa289 */
  Texitcoin: 696969,
  /** - | RGB on Bitcoin (mainnet) | 0x800c9f1e */
  RgbOnBitcoinMainnet: 827166,
  /** - | RGB on Bitcoin (testnet) | 0x800c9f1f */
  RgbOnBitcoinTestnet: 827167,
  /** - | RGB on Liquid (mainnet) | 0x800ca60e */
  RgbOnLiquidMainnet: 828942,
  /** SEA | Second Exchange Alliance | 0x800d9038 */
  SecondExchangeAlliance: 888888,
  /** AMAX | Armonia Meta Chain | 0x80100000 */
  ArmoniaMetaChain: 1048576,
  /** ILT | iOlite | 0x8011df89 */
  Iolite: 1171337,
  /** ETHO | Etho Protocol | 0x8014095a */
  EthoProtocol: 1313114,
  /** XERO | Xerom | 0x80140adc */
  Xerom: 1313500,
  /** LAX | LAPO | 0x801a2010 */
  Lapo: 1712144,
  /** EPK | EPIK Protocol | 0x803be02b */
  EpikProtocol: 3924011,
  /** BBLU | Bitcoin-Blu | 0x80426c63 */
  BitcoinBlu: 4353123,
  /** MCSH | MetaMask Cash Account | 0x80430452 */
  MetamaskCashAccount: 4392018,
  /** HYD | Hydra Token | 0x80485944 */
  HydraToken: 4741444,
  /** - | Miden | 0x804d444e */
  Miden: 5063758,
  /** BCO | BitcoinOre | 0x80501949 */
  Bitcoinore: 5249353,
  /** BHD | BitcoinHD | 0x8050194a */
  Bitcoinhd: 5249354,
  /** PTN | PalletOne | 0x8050544e */
  Palletone: 5264462,
  /** VLX | Velas | 0x80564c58 */
  Velas: 5655640,
  /** WAN | Wanchain | 0x8057414e */
  Wanchain: 5718350,
  /** WAVES | Waves | 0x80579bfc */
  Waves: 5741564,
  /** WEST | Waves Enterprise | 0x80579bfd */
  WavesEnterprise: 5741565,
  /** ABC | Abcmint | 0x80616263 */
  Abcmint: 6382179,
  /** CRM | Creamcoin | 0x8063726d */
  Creamcoin: 6517357,
  /** BROCK | Bitrock | 0x806d6e52 */
  Bitrock: 7171666,
  /** SEM | Semux | 0x8073656d */
  Semux: 7562605,
  /** ION | ION | 0x80737978 */
  Ion: 7567736,
  /** FCT | FirmaChain | 0x8076adf1 */
  Firmachain: 7777777,
  /** WGR | WGR | 0x80776772 */
  Wgr: 7825266,
  /** OBSR | OBServer | 0x80776773 */
  Observer: 7825267,
  /** AFS | ANFS | 0x807c8fc7 */
  Anfs: 8163271,
  /** BTCV | Bitcoin-Value | 0x807c8ff9 */
  BitcoinValue: 8163321,
  /** OSMO | Osmosis | 0x805d30b6 */
  Osmosis: 10000118,
  /** LBR | 0L | 0x80abcdef */
  Coin0l: 11259375,
  /** XDS | XDS | 0x80e6b280 */
  Xds: 15118976,
  /** SEI | SEI | 0x8121eb36 */
  Sei: 19000118,
  /** ROH | Rooch | 0x8134afd5 */
  Rooch: 20230101,
  /** NLK | NuLinkCoin | 0x8134d82e */
  Nulinkcoin: 20240430,
  /** DYDX | Dydx | 0x814fb1f6 */
  Dydx: 22000118,
  /** INJ | Injective | 0x814fb1f7 */
  Injective: 22000119,
  /** AXX | AtlasX Chain | 0x821f3680 */
  AtlasxChain: 35600000,
  /** AQUA | Aquachain | 0x83adbc39 */
  Aquachain: 61717561,
  /** AZT | Aztecoin | 0x84a2cb71 */
  Aztecoin: 77777777,
  /** HATCH | Hatch | 0x854c5638 */
  Hatch: 88888888,
  /** kUSD | kUSD | 0x857ab1e1 */
  Kusd: 91927009,
  /** GENS | GENS | 0x85f5e0fc */
  Gens: 99999996,
  /** EQ | EQ | 0x85f5e0fd */
  Eq: 99999997,
  /** FLUID | Fluid Chains | 0x85f5e0fe */
  FluidChains: 99999998,
  /** QKC | QuarkChain | 0x85f5e0ff */
  Quarkchain: 99999999,
  /** ZORK | Zork Network | 0x8e4f524b */
  ZorkNetwork: 240079435,
  /** MON | Monad | 0x90000143 */
  Monad: 268435779,
  /** FVDC | ForumCoin | 0xa4465644 */
  Forumcoin: 608589380,
  /** FAIC | Free AI Chain | 0xbc34eb12 */
  FreeAiChain: 1010101010,
  /** - | Fuel | 0xc655454c */
  Fuel: 1179993420,
  /** TTNC | TakeTitan | 0xc655454d */
  Taketitan: 1179993421,
  /** MTGBP | MTGBP | 0xc6554557 */
  Mtgbp: 1179993431,
  /** QFS | Qfs | 0xc6554561 */
  Qfs: 1179993441,
  /** RWA | Asset Chain | 0xc655456b */
  AssetChain: 1179993451,
  /** HXC | HuaXia Chain | 0xc6554575 */
  HuaxiaChain: 1179993461,
  /** AME | AME Chain | 0xc655457f */
  AmeChain: 1179993471,
  /** ATTO | Atto | 0xef747461 */
  Atto: 1869902945,
} as const;

export type Bip44CoinType = ValueOfEnum<typeof Bip44CoinType>;
