#!/usr/bin/env -S tsx

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

type Slip44Row = {
  index: number;
  hex: string;
  symbol: string;
  coin: string;
};

const SLIP44_URL = 'https://raw.githubusercontent.com/satoshilabs/slips/master/slip-0044.md';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const outputFilePath = path.resolve(__dirname, '../src/enums/Bip44CoinType.ts');

const toPascalCase = (value: string): string => {
  const normalized = value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim();

  if (!normalized) {
    return '';
  }

  return normalized
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => {
      const lower = part.toLowerCase();
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join('');
};

const makeKey = (row: Slip44Row, usedKeys: Set<string>): string => {
  if (row.index === 0) {
    usedKeys.add('Bitcoin');
    return 'Bitcoin';
  }

  if (row.index === 1) {
    usedKeys.add('BitcoinTestnet');
    return 'BitcoinTestnet';
  }

  let base = toPascalCase(row.coin);

  if (!base || base === 'Reserved') {
    base = toPascalCase(row.symbol);
  }

  if (!base) {
    base = `Coin${row.index}`;
  }

  if (/^\d/.test(base)) {
    base = `Coin${base}`;
  }

  let key = base;
  if (!usedKeys.has(key)) {
    usedKeys.add(key);
    return key;
  }

  key = `${base}${row.index}`;
  if (!usedKeys.has(key)) {
    usedKeys.add(key);
    return key;
  }

  let suffix = 2;
  while (usedKeys.has(`${key}${suffix}`)) {
    suffix += 1;
  }

  key = `${key}${suffix}`;
  usedKeys.add(key);
  return key;
};

const parseSlip44Table = (markdownText: string): Slip44Row[] => {
  const lines = markdownText.split(/\r?\n/);
  const rows: Slip44Row[] = [];
  let inTable = false;

  for (const line of lines) {
    if (!inTable && line.includes('| Coin type') && line.includes('| Coin')) {
      inTable = true;
      continue;
    }

    if (!inTable) {
      continue;
    }

    if (!line.trim().startsWith('|')) {
      if (rows.length > 0) {
        break;
      }

      continue;
    }

    const cells = line
      .split('|')
      .slice(1, -1)
      .map((cell) => cell.trim());

    if (cells.length < 4 || cells[0] === 'Coin type' || /^-+$/.test(cells[0])) {
      continue;
    }

    const index = Number.parseInt(cells[0], 10);
    if (!Number.isInteger(index)) {
      continue;
    }

    rows.push({
      index,
      hex: cells[1] || '',
      symbol: cells[2] || '',
      coin: cells[3] || '',
    });
  }

  if (rows.length === 0) {
    throw new Error('Could not parse any coin type rows from SLIP-0044 markdown');
  }

  return rows;
};

const buildBip44CoinTypeFile = (rows: Slip44Row[]): string => {
  const usedKeys = new Set<string>();

  const entries = rows
    .sort((a, b) => a.index - b.index)
    .map((row) => {
      const key = makeKey(row, usedKeys);
      const symbol = row.symbol || '-';
      const coin = row.coin || '-';

      return `  /** ${symbol} | ${coin} | ${row.hex} */\n  ${key}: ${row.index},`;
    })
    .join('\n');

  return [
    "import type { ValueOfEnum } from '@repo/types';",
    '',
    '/**',
    ' * Generated by scripts/generate-slip44-enums.ts from SLIP-0044.',
    ' * Do not edit manually.',
    ' * @see https://raw.githubusercontent.com/satoshilabs/slips/master/slip-0044.md',
    ' */',
    'export const Bip44CoinType = {',
    entries,
    '} as const;',
    '',
    'export type Bip44CoinType = ValueOfEnum<typeof Bip44CoinType>;',
    '',
  ].join('\n');
};

const run = async (): Promise<void> => {
  const args = new Set(process.argv.slice(2));
  const response = await fetch(SLIP44_URL);

  if (!response.ok) {
    throw new Error(`Failed to fetch SLIP-0044 (${response.status})`);
  }

  const markdown = await response.text();
  const rows = parseSlip44Table(markdown);
  const generated = buildBip44CoinTypeFile(rows);

  if (args.has('--stdout')) {
    process.stdout.write(generated);
    return;
  }

  if (args.has('--check')) {
    const current = await readFile(outputFilePath, 'utf8');
    if (current !== generated) {
      throw new Error('Bip44CoinType.ts is out of date. Run generate:slip44 to update it.');
    }

    process.stdout.write('Bip44CoinType.ts is up to date.\n');
    return;
  }

  await writeFile(outputFilePath, generated, 'utf8');
  process.stdout.write(`Wrote ${rows.length} SLIP-0044 entries to ${outputFilePath}\n`);
};

run().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`${message}\n`);
  process.exit(1);
});
